// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: v2/pilot.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StreamKind int32

const (
	StreamKind_STREAM_UNKNOWN StreamKind = 0
	// Auth — first stream the worker opens after the session is up.
	StreamKind_STREAM_REGISTER StreamKind = 1
	// Server → worker requests:
	StreamKind_STREAM_RESOURCE_REQUEST StreamKind = 10
	StreamKind_STREAM_HTTP_REQUEST     StreamKind = 11
	StreamKind_STREAM_PLUGIN_COMMAND   StreamKind = 12
	StreamKind_STREAM_POD_LOGS         StreamKind = 13
	StreamKind_STREAM_POD_EXEC         StreamKind = 14
	StreamKind_STREAM_WS_PROXY         StreamKind = 15
	// Worker → server pushes:
	StreamKind_STREAM_PLUGIN_STATUS_PUSH StreamKind = 20
	StreamKind_STREAM_PLUGIN_LOG_PUSH    StreamKind = 21
)

// Enum value maps for StreamKind.
var (
	StreamKind_name = map[int32]string{
		0:  "STREAM_UNKNOWN",
		1:  "STREAM_REGISTER",
		10: "STREAM_RESOURCE_REQUEST",
		11: "STREAM_HTTP_REQUEST",
		12: "STREAM_PLUGIN_COMMAND",
		13: "STREAM_POD_LOGS",
		14: "STREAM_POD_EXEC",
		15: "STREAM_WS_PROXY",
		20: "STREAM_PLUGIN_STATUS_PUSH",
		21: "STREAM_PLUGIN_LOG_PUSH",
	}
	StreamKind_value = map[string]int32{
		"STREAM_UNKNOWN":            0,
		"STREAM_REGISTER":           1,
		"STREAM_RESOURCE_REQUEST":   10,
		"STREAM_HTTP_REQUEST":       11,
		"STREAM_PLUGIN_COMMAND":     12,
		"STREAM_POD_LOGS":           13,
		"STREAM_POD_EXEC":           14,
		"STREAM_WS_PROXY":           15,
		"STREAM_PLUGIN_STATUS_PUSH": 20,
		"STREAM_PLUGIN_LOG_PUSH":    21,
	}
)

func (x StreamKind) Enum() *StreamKind {
	p := new(StreamKind)
	*p = x
	return p
}

func (x StreamKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StreamKind) Descriptor() protoreflect.EnumDescriptor {
	return file_v2_pilot_proto_enumTypes[0].Descriptor()
}

func (StreamKind) Type() protoreflect.EnumType {
	return &file_v2_pilot_proto_enumTypes[0]
}

func (x StreamKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StreamKind.Descriptor instead.
func (StreamKind) EnumDescriptor() ([]byte, []int) {
	return file_v2_pilot_proto_rawDescGZIP(), []int{0}
}

// StreamHeader is the discriminator both peers exchange before any
// RPC-specific traffic flows. It tells the receiver what protocol to
// expect on the rest of the stream and whether to wrap reads / writes
// in gzip. The header itself is always plaintext (so the gzip decision
// is bootstrappable).
type StreamHeader struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Kind  StreamKind             `protobuf:"varint,1,opt,name=kind,proto3,enum=pilot.v2.StreamKind" json:"kind,omitempty"`
	// Application-level RPC id, useful for cross-log correlation only —
	// yamux assigns its own stream id for routing. Worker-initiated push
	// streams (PLUGIN_STATUS_PUSH, PLUGIN_LOG_PUSH) leave this empty.
	RequestId string `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// Negotiated gzip for the rest of the stream. Sender chooses based on
	// payload type — JSON / text streams gzip well (5-8× on cross-WAN),
	// binary blobs and interactive sessions skip it.
	Gzip          bool `protobuf:"varint,3,opt,name=gzip,proto3" json:"gzip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamHeader) Reset() {
	*x = StreamHeader{}
	mi := &file_v2_pilot_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamHeader) ProtoMessage() {}

func (x *StreamHeader) ProtoReflect() protoreflect.Message {
	mi := &file_v2_pilot_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamHeader.ProtoReflect.Descriptor instead.
func (*StreamHeader) Descriptor() ([]byte, []int) {
	return file_v2_pilot_proto_rawDescGZIP(), []int{0}
}

func (x *StreamHeader) GetKind() StreamKind {
	if x != nil {
		return x.Kind
	}
	return StreamKind_STREAM_UNKNOWN
}

func (x *StreamHeader) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *StreamHeader) GetGzip() bool {
	if x != nil {
		return x.Gzip
	}
	return false
}

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClusterToken  string                 `protobuf:"bytes,1,opt,name=cluster_token,json=clusterToken,proto3" json:"cluster_token,omitempty"`
	WorkerVersion string                 `protobuf:"bytes,2,opt,name=worker_version,json=workerVersion,proto3" json:"worker_version,omitempty"`
	// K8s DNS suffix the worker's kubelet reports as --cluster-domain.
	// Server uses this when constructing in-cluster Service FQDNs.
	ClusterDomain string `protobuf:"bytes,3,opt,name=cluster_domain,json=clusterDomain,proto3" json:"cluster_domain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_v2_pilot_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v2_pilot_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_v2_pilot_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterRequest) GetClusterToken() string {
	if x != nil {
		return x.ClusterToken
	}
	return ""
}

func (x *RegisterRequest) GetWorkerVersion() string {
	if x != nil {
		return x.WorkerVersion
	}
	return ""
}

func (x *RegisterRequest) GetClusterDomain() string {
	if x != nil {
		return x.ClusterDomain
	}
	return ""
}

type RegisterAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ClusterId     string                 `protobuf:"bytes,2,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterAck) Reset() {
	*x = RegisterAck{}
	mi := &file_v2_pilot_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterAck) ProtoMessage() {}

func (x *RegisterAck) ProtoReflect() protoreflect.Message {
	mi := &file_v2_pilot_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterAck.ProtoReflect.Descriptor instead.
func (*RegisterAck) Descriptor() ([]byte, []int) {
	return file_v2_pilot_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterAck) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterAck) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *RegisterAck) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ResourceRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Action    string                 `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"` // list / get / apply / update / patch / delete / describe / list-full
	Group     string                 `protobuf:"bytes,2,opt,name=group,proto3" json:"group,omitempty"`
	Version   string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Kind      string                 `protobuf:"bytes,4,opt,name=kind,proto3" json:"kind,omitempty"`
	Namespace string                 `protobuf:"bytes,5,opt,name=namespace,proto3" json:"namespace,omitempty"` // empty = cluster-scoped
	Name      string                 `protobuf:"bytes,6,opt,name=name,proto3" json:"name,omitempty"`           // empty for list
	// list pagination: 0 = unbounded; non-empty continue_token = next page
	Limit         int64  `protobuf:"varint,7,opt,name=limit,proto3" json:"limit,omitempty"`
	ContinueToken string `protobuf:"bytes,8,opt,name=continue_token,json=continueToken,proto3" json:"continue_token,omitempty"`
	// K8s label selector ("key=value,key2!=value2"); list actions only.
	LabelSelector string `protobuf:"bytes,9,opt,name=label_selector,json=labelSelector,proto3" json:"label_selector,omitempty"`
	// body_size hints whether to expect raw body bytes after this frame.
	// 0 = no body; >0 = exactly this many bytes follow (apply / update /
	// patch JSON). Receiver reads body_size bytes then either continues
	// dispatching or waits for half-close.
	BodySize      int64 `protobuf:"varint,10,opt,name=body_size,json=bodySize,proto3" json:"body_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceRequest) Reset() {
	*x = ResourceRequest{}
	mi := &file_v2_pilot_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceRequest) ProtoMessage() {}

func (x *ResourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v2_pilot_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceRequest.ProtoReflect.Descriptor instead.
func (*ResourceRequest) Descriptor() ([]byte, []int) {
	return file_v2_pilot_proto_rawDescGZIP(), []int{3}
}

func (x *ResourceRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *ResourceRequest) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *ResourceRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ResourceRequest) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *ResourceRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *ResourceRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ResourceRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ResourceRequest) GetContinueToken() string {
	if x != nil {
		return x.ContinueToken
	}
	return ""
}

func (x *ResourceRequest) GetLabelSelector() string {
	if x != nil {
		return x.LabelSelector
	}
	return ""
}

func (x *ResourceRequest) GetBodySize() int64 {
	if x != nil {
		return x.BodySize
	}
	return 0
}

type ResourceResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Success bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error   string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	// body_size of the payload bytes that follow this frame on the wire.
	// 0 = no body (delete / error case).
	BodySize      int64 `protobuf:"varint,3,opt,name=body_size,json=bodySize,proto3" json:"body_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceResponse) Reset() {
	*x = ResourceResponse{}
	mi := &file_v2_pilot_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceResponse) ProtoMessage() {}

func (x *ResourceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v2_pilot_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceResponse.ProtoReflect.Descriptor instead.
func (*ResourceResponse) Descriptor() ([]byte, []int) {
	return file_v2_pilot_proto_rawDescGZIP(), []int{4}
}

func (x *ResourceResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ResourceResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ResourceResponse) GetBodySize() int64 {
	if x != nil {
		return x.BodySize
	}
	return 0
}

type HTTPHeader struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HTTPHeader) Reset() {
	*x = HTTPHeader{}
	mi := &file_v2_pilot_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HTTPHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HTTPHeader) ProtoMessage() {}

func (x *HTTPHeader) ProtoReflect() protoreflect.Message {
	mi := &file_v2_pilot_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HTTPHeader.ProtoReflect.Descriptor instead.
func (*HTTPHeader) Descriptor() ([]byte, []int) {
	return file_v2_pilot_proto_rawDescGZIP(), []int{5}
}

func (x *HTTPHeader) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *HTTPHeader) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type HTTPRequestStart struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Method  string                 `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	Url     string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Headers []*HTTPHeader          `protobuf:"bytes,3,rep,name=headers,proto3" json:"headers,omitempty"`
	// body_size of bytes that follow (0 = no body).
	BodySize int64 `protobuf:"varint,4,opt,name=body_size,json=bodySize,proto3" json:"body_size,omitempty"`
	// True → worker forwards response body live; false → buffered.
	StreamResponse bool `protobuf:"varint,5,opt,name=stream_response,json=streamResponse,proto3" json:"stream_response,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HTTPRequestStart) Reset() {
	*x = HTTPRequestStart{}
	mi := &file_v2_pilot_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HTTPRequestStart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HTTPRequestStart) ProtoMessage() {}

func (x *HTTPRequestStart) ProtoReflect() protoreflect.Message {
	mi := &file_v2_pilot_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HTTPRequestStart.ProtoReflect.Descriptor instead.
func (*HTTPRequestStart) Descriptor() ([]byte, []int) {
	return file_v2_pilot_proto_rawDescGZIP(), []int{6}
}

func (x *HTTPRequestStart) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *HTTPRequestStart) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *HTTPRequestStart) GetHeaders() []*HTTPHeader {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *HTTPRequestStart) GetBodySize() int64 {
	if x != nil {
		return x.BodySize
	}
	return 0
}

func (x *HTTPRequestStart) GetStreamResponse() bool {
	if x != nil {
		return x.StreamResponse
	}
	return false
}

type HTTPResponseStart struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Status  int32                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Headers []*HTTPHeader          `protobuf:"bytes,2,rep,name=headers,proto3" json:"headers,omitempty"`
	// Empty on success. Non-empty when the worker failed before reading
	// any upstream bytes (DNS / connect / timeout). Receiver should NOT
	// expect a body in that case.
	Error string `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	// For buffered responses: the exact byte count that follows. For
	// streaming responses: -1 (caller reads until stream close).
	BodySize      int64 `protobuf:"varint,4,opt,name=body_size,json=bodySize,proto3" json:"body_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HTTPResponseStart) Reset() {
	*x = HTTPResponseStart{}
	mi := &file_v2_pilot_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HTTPResponseStart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HTTPResponseStart) ProtoMessage() {}

func (x *HTTPResponseStart) ProtoReflect() protoreflect.Message {
	mi := &file_v2_pilot_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HTTPResponseStart.ProtoReflect.Descriptor instead.
func (*HTTPResponseStart) Descriptor() ([]byte, []int) {
	return file_v2_pilot_proto_rawDescGZIP(), []int{7}
}

func (x *HTTPResponseStart) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *HTTPResponseStart) GetHeaders() []*HTTPHeader {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *HTTPResponseStart) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *HTTPResponseStart) GetBodySize() int64 {
	if x != nil {
		return x.BodySize
	}
	return 0
}

type PluginCommand struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Action  string                 `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"` // "enable" or "disable"
	CrdName string                 `protobuf:"bytes,2,opt,name=crd_name,json=crdName,proto3" json:"crd_name,omitempty"`
	Spec    *PluginSpec            `protobuf:"bytes,3,opt,name=spec,proto3" json:"spec,omitempty"` // only for enable
	// chart_blob_size: bytes of .tgz that follow this frame. 0 = no blob
	// (either disable, or worker already has it cached by sha256).
	ChartBlobSize int64 `protobuf:"varint,4,opt,name=chart_blob_size,json=chartBlobSize,proto3" json:"chart_blob_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginCommand) Reset() {
	*x = PluginCommand{}
	mi := &file_v2_pilot_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginCommand) ProtoMessage() {}

func (x *PluginCommand) ProtoReflect() protoreflect.Message {
	mi := &file_v2_pilot_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginCommand.ProtoReflect.Descriptor instead.
func (*PluginCommand) Descriptor() ([]byte, []int) {
	return file_v2_pilot_proto_rawDescGZIP(), []int{8}
}

func (x *PluginCommand) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *PluginCommand) GetCrdName() string {
	if x != nil {
		return x.CrdName
	}
	return ""
}

func (x *PluginCommand) GetSpec() *PluginSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *PluginCommand) GetChartBlobSize() int64 {
	if x != nil {
		return x.ChartBlobSize
	}
	return 0
}

type PluginSpec struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	PluginId         string                 `protobuf:"bytes,1,opt,name=plugin_id,json=pluginId,proto3" json:"plugin_id,omitempty"`
	DisplayName      string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Chart            *ChartSource           `protobuf:"bytes,3,opt,name=chart,proto3" json:"chart,omitempty"`
	ReleaseName      string                 `protobuf:"bytes,4,opt,name=release_name,json=releaseName,proto3" json:"release_name,omitempty"`
	ReleaseNamespace string                 `protobuf:"bytes,5,opt,name=release_namespace,json=releaseNamespace,proto3" json:"release_namespace,omitempty"`
	Values           string                 `protobuf:"bytes,6,opt,name=values,proto3" json:"values,omitempty"` // YAML text
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PluginSpec) Reset() {
	*x = PluginSpec{}
	mi := &file_v2_pilot_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginSpec) ProtoMessage() {}

func (x *PluginSpec) ProtoReflect() protoreflect.Message {
	mi := &file_v2_pilot_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginSpec.ProtoReflect.Descriptor instead.
func (*PluginSpec) Descriptor() ([]byte, []int) {
	return file_v2_pilot_proto_rawDescGZIP(), []int{9}
}

func (x *PluginSpec) GetPluginId() string {
	if x != nil {
		return x.PluginId
	}
	return ""
}

func (x *PluginSpec) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *PluginSpec) GetChart() *ChartSource {
	if x != nil {
		return x.Chart
	}
	return nil
}

func (x *PluginSpec) GetReleaseName() string {
	if x != nil {
		return x.ReleaseName
	}
	return ""
}

func (x *PluginSpec) GetReleaseNamespace() string {
	if x != nil {
		return x.ReleaseNamespace
	}
	return ""
}

func (x *PluginSpec) GetValues() string {
	if x != nil {
		return x.Values
	}
	return ""
}

type ChartSource struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Type    string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"` // "repo" / "local"
	Repo    string                 `protobuf:"bytes,2,opt,name=repo,proto3" json:"repo,omitempty"` // type=repo
	Name    string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Version string                 `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	Sha256  string                 `protobuf:"bytes,5,opt,name=sha256,proto3" json:"sha256,omitempty"` // type=local
	// When true and chart_blob_size > 0, the raw .tgz bytes follow the
	// PluginCommand frame on the same stream.
	HasBlob       bool `protobuf:"varint,6,opt,name=has_blob,json=hasBlob,proto3" json:"has_blob,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChartSource) Reset() {
	*x = ChartSource{}
	mi := &file_v2_pilot_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChartSource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChartSource) ProtoMessage() {}

func (x *ChartSource) ProtoReflect() protoreflect.Message {
	mi := &file_v2_pilot_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChartSource.ProtoReflect.Descriptor instead.
func (*ChartSource) Descriptor() ([]byte, []int) {
	return file_v2_pilot_proto_rawDescGZIP(), []int{10}
}

func (x *ChartSource) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ChartSource) GetRepo() string {
	if x != nil {
		return x.Repo
	}
	return ""
}

func (x *ChartSource) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ChartSource) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ChartSource) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

func (x *ChartSource) GetHasBlob() bool {
	if x != nil {
		return x.HasBlob
	}
	return false
}

type PluginCommandAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginCommandAck) Reset() {
	*x = PluginCommandAck{}
	mi := &file_v2_pilot_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginCommandAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginCommandAck) ProtoMessage() {}

func (x *PluginCommandAck) ProtoReflect() protoreflect.Message {
	mi := &file_v2_pilot_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginCommandAck.ProtoReflect.Descriptor instead.
func (*PluginCommandAck) Descriptor() ([]byte, []int) {
	return file_v2_pilot_proto_rawDescGZIP(), []int{11}
}

func (x *PluginCommandAck) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PluginCommandAck) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type LogsStartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Pod           string                 `protobuf:"bytes,2,opt,name=pod,proto3" json:"pod,omitempty"`
	Container     string                 `protobuf:"bytes,3,opt,name=container,proto3" json:"container,omitempty"` // empty = first/default
	Follow        bool                   `protobuf:"varint,4,opt,name=follow,proto3" json:"follow,omitempty"`
	TailLines     int64                  `protobuf:"varint,5,opt,name=tail_lines,json=tailLines,proto3" json:"tail_lines,omitempty"`
	SinceSeconds  int64                  `protobuf:"varint,6,opt,name=since_seconds,json=sinceSeconds,proto3" json:"since_seconds,omitempty"`
	Previous      bool                   `protobuf:"varint,7,opt,name=previous,proto3" json:"previous,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogsStartRequest) Reset() {
	*x = LogsStartRequest{}
	mi := &file_v2_pilot_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogsStartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogsStartRequest) ProtoMessage() {}

func (x *LogsStartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v2_pilot_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogsStartRequest.ProtoReflect.Descriptor instead.
func (*LogsStartRequest) Descriptor() ([]byte, []int) {
	return file_v2_pilot_proto_rawDescGZIP(), []int{12}
}

func (x *LogsStartRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *LogsStartRequest) GetPod() string {
	if x != nil {
		return x.Pod
	}
	return ""
}

func (x *LogsStartRequest) GetContainer() string {
	if x != nil {
		return x.Container
	}
	return ""
}

func (x *LogsStartRequest) GetFollow() bool {
	if x != nil {
		return x.Follow
	}
	return false
}

func (x *LogsStartRequest) GetTailLines() int64 {
	if x != nil {
		return x.TailLines
	}
	return 0
}

func (x *LogsStartRequest) GetSinceSeconds() int64 {
	if x != nil {
		return x.SinceSeconds
	}
	return 0
}

func (x *LogsStartRequest) GetPrevious() bool {
	if x != nil {
		return x.Previous
	}
	return false
}

type LogsChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogsChunk) Reset() {
	*x = LogsChunk{}
	mi := &file_v2_pilot_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogsChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogsChunk) ProtoMessage() {}

func (x *LogsChunk) ProtoReflect() protoreflect.Message {
	mi := &file_v2_pilot_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogsChunk.ProtoReflect.Descriptor instead.
func (*LogsChunk) Descriptor() ([]byte, []int) {
	return file_v2_pilot_proto_rawDescGZIP(), []int{13}
}

func (x *LogsChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type LogsEnd struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"` // empty = clean EOF
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogsEnd) Reset() {
	*x = LogsEnd{}
	mi := &file_v2_pilot_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogsEnd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogsEnd) ProtoMessage() {}

func (x *LogsEnd) ProtoReflect() protoreflect.Message {
	mi := &file_v2_pilot_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogsEnd.ProtoReflect.Descriptor instead.
func (*LogsEnd) Descriptor() ([]byte, []int) {
	return file_v2_pilot_proto_rawDescGZIP(), []int{14}
}

func (x *LogsEnd) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ExecStartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Pod           string                 `protobuf:"bytes,2,opt,name=pod,proto3" json:"pod,omitempty"`
	Container     string                 `protobuf:"bytes,3,opt,name=container,proto3" json:"container,omitempty"`
	Command       []string               `protobuf:"bytes,4,rep,name=command,proto3" json:"command,omitempty"`
	Tty           bool                   `protobuf:"varint,5,opt,name=tty,proto3" json:"tty,omitempty"`
	Cols          uint32                 `protobuf:"varint,6,opt,name=cols,proto3" json:"cols,omitempty"`
	Rows          uint32                 `protobuf:"varint,7,opt,name=rows,proto3" json:"rows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecStartRequest) Reset() {
	*x = ExecStartRequest{}
	mi := &file_v2_pilot_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecStartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecStartRequest) ProtoMessage() {}

func (x *ExecStartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v2_pilot_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecStartRequest.ProtoReflect.Descriptor instead.
func (*ExecStartRequest) Descriptor() ([]byte, []int) {
	return file_v2_pilot_proto_rawDescGZIP(), []int{15}
}

func (x *ExecStartRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *ExecStartRequest) GetPod() string {
	if x != nil {
		return x.Pod
	}
	return ""
}

func (x *ExecStartRequest) GetContainer() string {
	if x != nil {
		return x.Container
	}
	return ""
}

func (x *ExecStartRequest) GetCommand() []string {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *ExecStartRequest) GetTty() bool {
	if x != nil {
		return x.Tty
	}
	return false
}

func (x *ExecStartRequest) GetCols() uint32 {
	if x != nil {
		return x.Cols
	}
	return 0
}

func (x *ExecStartRequest) GetRows() uint32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

type ExecStdin struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecStdin) Reset() {
	*x = ExecStdin{}
	mi := &file_v2_pilot_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecStdin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecStdin) ProtoMessage() {}

func (x *ExecStdin) ProtoReflect() protoreflect.Message {
	mi := &file_v2_pilot_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecStdin.ProtoReflect.Descriptor instead.
func (*ExecStdin) Descriptor() ([]byte, []int) {
	return file_v2_pilot_proto_rawDescGZIP(), []int{16}
}

func (x *ExecStdin) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type ExecResize struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cols          uint32                 `protobuf:"varint,1,opt,name=cols,proto3" json:"cols,omitempty"`
	Rows          uint32                 `protobuf:"varint,2,opt,name=rows,proto3" json:"rows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecResize) Reset() {
	*x = ExecResize{}
	mi := &file_v2_pilot_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecResize) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecResize) ProtoMessage() {}

func (x *ExecResize) ProtoReflect() protoreflect.Message {
	mi := &file_v2_pilot_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecResize.ProtoReflect.Descriptor instead.
func (*ExecResize) Descriptor() ([]byte, []int) {
	return file_v2_pilot_proto_rawDescGZIP(), []int{17}
}

func (x *ExecResize) GetCols() uint32 {
	if x != nil {
		return x.Cols
	}
	return 0
}

func (x *ExecResize) GetRows() uint32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

type ExecOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stream        uint32                 `protobuf:"varint,1,opt,name=stream,proto3" json:"stream,omitempty"` // 1=stdout, 2=stderr
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecOutput) Reset() {
	*x = ExecOutput{}
	mi := &file_v2_pilot_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecOutput) ProtoMessage() {}

func (x *ExecOutput) ProtoReflect() protoreflect.Message {
	mi := &file_v2_pilot_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecOutput.ProtoReflect.Descriptor instead.
func (*ExecOutput) Descriptor() ([]byte, []int) {
	return file_v2_pilot_proto_rawDescGZIP(), []int{18}
}

func (x *ExecOutput) GetStream() uint32 {
	if x != nil {
		return x.Stream
	}
	return 0
}

func (x *ExecOutput) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type ExecEnd struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExitCode      int32                  `protobuf:"varint,1,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecEnd) Reset() {
	*x = ExecEnd{}
	mi := &file_v2_pilot_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecEnd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecEnd) ProtoMessage() {}

func (x *ExecEnd) ProtoReflect() protoreflect.Message {
	mi := &file_v2_pilot_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecEnd.ProtoReflect.Descriptor instead.
func (*ExecEnd) Descriptor() ([]byte, []int) {
	return file_v2_pilot_proto_rawDescGZIP(), []int{19}
}

func (x *ExecEnd) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *ExecEnd) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type WSStartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Headers       []*HTTPHeader          `protobuf:"bytes,2,rep,name=headers,proto3" json:"headers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WSStartRequest) Reset() {
	*x = WSStartRequest{}
	mi := &file_v2_pilot_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WSStartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WSStartRequest) ProtoMessage() {}

func (x *WSStartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v2_pilot_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WSStartRequest.ProtoReflect.Descriptor instead.
func (*WSStartRequest) Descriptor() ([]byte, []int) {
	return file_v2_pilot_proto_rawDescGZIP(), []int{20}
}

func (x *WSStartRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *WSStartRequest) GetHeaders() []*HTTPHeader {
	if x != nil {
		return x.Headers
	}
	return nil
}

type WSFrame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Opcode        int32                  `protobuf:"varint,1,opt,name=opcode,proto3" json:"opcode,omitempty"` // RFC 6455: 1=text, 2=binary
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WSFrame) Reset() {
	*x = WSFrame{}
	mi := &file_v2_pilot_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WSFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WSFrame) ProtoMessage() {}

func (x *WSFrame) ProtoReflect() protoreflect.Message {
	mi := &file_v2_pilot_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WSFrame.ProtoReflect.Descriptor instead.
func (*WSFrame) Descriptor() ([]byte, []int) {
	return file_v2_pilot_proto_rawDescGZIP(), []int{21}
}

func (x *WSFrame) GetOpcode() int32 {
	if x != nil {
		return x.Opcode
	}
	return 0
}

func (x *WSFrame) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type WSEnd struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WSEnd) Reset() {
	*x = WSEnd{}
	mi := &file_v2_pilot_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WSEnd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WSEnd) ProtoMessage() {}

func (x *WSEnd) ProtoReflect() protoreflect.Message {
	mi := &file_v2_pilot_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WSEnd.ProtoReflect.Descriptor instead.
func (*WSEnd) Descriptor() ([]byte, []int) {
	return file_v2_pilot_proto_rawDescGZIP(), []int{22}
}

func (x *WSEnd) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *WSEnd) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type PluginStatusPush struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	CrdName string                 `protobuf:"bytes,1,opt,name=crd_name,json=crdName,proto3" json:"crd_name,omitempty"`
	Phase   string                 `protobuf:"bytes,2,opt,name=phase,proto3" json:"phase,omitempty"` // Pending / Installing / Running / Upgrading / Failed / Uninstalling
	Message string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	// Helm release version actually installed (chart-side, not the CRD spec).
	ObservedVersion string `protobuf:"bytes,4,opt,name=observed_version,json=observedVersion,proto3" json:"observed_version,omitempty"`
	// sha256 of the values YAML actually applied — server detects drift.
	ObservedValuesHash string `protobuf:"bytes,5,opt,name=observed_values_hash,json=observedValuesHash,proto3" json:"observed_values_hash,omitempty"`
	HelmRevision       int32  `protobuf:"varint,6,opt,name=helm_revision,json=helmRevision,proto3" json:"helm_revision,omitempty"`
	InstalledAt        int64  `protobuf:"varint,7,opt,name=installed_at,json=installedAt,proto3" json:"installed_at,omitempty"`         // unix seconds, 0 if not installed
	LastUpdatedAt      int64  `protobuf:"varint,8,opt,name=last_updated_at,json=lastUpdatedAt,proto3" json:"last_updated_at,omitempty"` // unix seconds
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *PluginStatusPush) Reset() {
	*x = PluginStatusPush{}
	mi := &file_v2_pilot_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginStatusPush) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginStatusPush) ProtoMessage() {}

func (x *PluginStatusPush) ProtoReflect() protoreflect.Message {
	mi := &file_v2_pilot_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginStatusPush.ProtoReflect.Descriptor instead.
func (*PluginStatusPush) Descriptor() ([]byte, []int) {
	return file_v2_pilot_proto_rawDescGZIP(), []int{23}
}

func (x *PluginStatusPush) GetCrdName() string {
	if x != nil {
		return x.CrdName
	}
	return ""
}

func (x *PluginStatusPush) GetPhase() string {
	if x != nil {
		return x.Phase
	}
	return ""
}

func (x *PluginStatusPush) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *PluginStatusPush) GetObservedVersion() string {
	if x != nil {
		return x.ObservedVersion
	}
	return ""
}

func (x *PluginStatusPush) GetObservedValuesHash() string {
	if x != nil {
		return x.ObservedValuesHash
	}
	return ""
}

func (x *PluginStatusPush) GetHelmRevision() int32 {
	if x != nil {
		return x.HelmRevision
	}
	return 0
}

func (x *PluginStatusPush) GetInstalledAt() int64 {
	if x != nil {
		return x.InstalledAt
	}
	return 0
}

func (x *PluginStatusPush) GetLastUpdatedAt() int64 {
	if x != nil {
		return x.LastUpdatedAt
	}
	return 0
}

type PluginLogChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CrdName       string                 `protobuf:"bytes,1,opt,name=crd_name,json=crdName,proto3" json:"crd_name,omitempty"`
	Level         string                 `protobuf:"bytes,2,opt,name=level,proto3" json:"level,omitempty"` // "info" / "warn" / "error"
	Ts            int64                  `protobuf:"varint,3,opt,name=ts,proto3" json:"ts,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginLogChunk) Reset() {
	*x = PluginLogChunk{}
	mi := &file_v2_pilot_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginLogChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginLogChunk) ProtoMessage() {}

func (x *PluginLogChunk) ProtoReflect() protoreflect.Message {
	mi := &file_v2_pilot_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginLogChunk.ProtoReflect.Descriptor instead.
func (*PluginLogChunk) Descriptor() ([]byte, []int) {
	return file_v2_pilot_proto_rawDescGZIP(), []int{24}
}

func (x *PluginLogChunk) GetCrdName() string {
	if x != nil {
		return x.CrdName
	}
	return ""
}

func (x *PluginLogChunk) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *PluginLogChunk) GetTs() int64 {
	if x != nil {
		return x.Ts
	}
	return 0
}

func (x *PluginLogChunk) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type PluginLogEnd struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CrdName       string                 `protobuf:"bytes,1,opt,name=crd_name,json=crdName,proto3" json:"crd_name,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Summary       string                 `protobuf:"bytes,3,opt,name=summary,proto3" json:"summary,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginLogEnd) Reset() {
	*x = PluginLogEnd{}
	mi := &file_v2_pilot_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginLogEnd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginLogEnd) ProtoMessage() {}

func (x *PluginLogEnd) ProtoReflect() protoreflect.Message {
	mi := &file_v2_pilot_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginLogEnd.ProtoReflect.Descriptor instead.
func (*PluginLogEnd) Descriptor() ([]byte, []int) {
	return file_v2_pilot_proto_rawDescGZIP(), []int{25}
}

func (x *PluginLogEnd) GetCrdName() string {
	if x != nil {
		return x.CrdName
	}
	return ""
}

func (x *PluginLogEnd) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PluginLogEnd) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

var File_v2_pilot_proto protoreflect.FileDescriptor

const file_v2_pilot_proto_rawDesc = "" +
	"\n" +
	"\x0ev2/pilot.proto\x12\bpilot.v2\"k\n" +
	"\fStreamHeader\x12(\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x14.pilot.v2.StreamKindR\x04kind\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\tR\trequestId\x12\x12\n" +
	"\x04gzip\x18\x03 \x01(\bR\x04gzip\"\x84\x01\n" +
	"\x0fRegisterRequest\x12#\n" +
	"\rcluster_token\x18\x01 \x01(\tR\fclusterToken\x12%\n" +
	"\x0eworker_version\x18\x02 \x01(\tR\rworkerVersion\x12%\n" +
	"\x0ecluster_domain\x18\x03 \x01(\tR\rclusterDomain\"`\n" +
	"\vRegisterAck\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x02 \x01(\tR\tclusterId\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\xa0\x02\n" +
	"\x0fResourceRequest\x12\x16\n" +
	"\x06action\x18\x01 \x01(\tR\x06action\x12\x14\n" +
	"\x05group\x18\x02 \x01(\tR\x05group\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12\x12\n" +
	"\x04kind\x18\x04 \x01(\tR\x04kind\x12\x1c\n" +
	"\tnamespace\x18\x05 \x01(\tR\tnamespace\x12\x12\n" +
	"\x04name\x18\x06 \x01(\tR\x04name\x12\x14\n" +
	"\x05limit\x18\a \x01(\x03R\x05limit\x12%\n" +
	"\x0econtinue_token\x18\b \x01(\tR\rcontinueToken\x12%\n" +
	"\x0elabel_selector\x18\t \x01(\tR\rlabelSelector\x12\x1b\n" +
	"\tbody_size\x18\n" +
	" \x01(\x03R\bbodySize\"_\n" +
	"\x10ResourceResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x1b\n" +
	"\tbody_size\x18\x03 \x01(\x03R\bbodySize\"6\n" +
	"\n" +
	"HTTPHeader\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"\xb2\x01\n" +
	"\x10HTTPRequestStart\x12\x16\n" +
	"\x06method\x18\x01 \x01(\tR\x06method\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12.\n" +
	"\aheaders\x18\x03 \x03(\v2\x14.pilot.v2.HTTPHeaderR\aheaders\x12\x1b\n" +
	"\tbody_size\x18\x04 \x01(\x03R\bbodySize\x12'\n" +
	"\x0fstream_response\x18\x05 \x01(\bR\x0estreamResponse\"\x8e\x01\n" +
	"\x11HTTPResponseStart\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x05R\x06status\x12.\n" +
	"\aheaders\x18\x02 \x03(\v2\x14.pilot.v2.HTTPHeaderR\aheaders\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\x12\x1b\n" +
	"\tbody_size\x18\x04 \x01(\x03R\bbodySize\"\x94\x01\n" +
	"\rPluginCommand\x12\x16\n" +
	"\x06action\x18\x01 \x01(\tR\x06action\x12\x19\n" +
	"\bcrd_name\x18\x02 \x01(\tR\acrdName\x12(\n" +
	"\x04spec\x18\x03 \x01(\v2\x14.pilot.v2.PluginSpecR\x04spec\x12&\n" +
	"\x0fchart_blob_size\x18\x04 \x01(\x03R\rchartBlobSize\"\xe1\x01\n" +
	"\n" +
	"PluginSpec\x12\x1b\n" +
	"\tplugin_id\x18\x01 \x01(\tR\bpluginId\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12+\n" +
	"\x05chart\x18\x03 \x01(\v2\x15.pilot.v2.ChartSourceR\x05chart\x12!\n" +
	"\frelease_name\x18\x04 \x01(\tR\vreleaseName\x12+\n" +
	"\x11release_namespace\x18\x05 \x01(\tR\x10releaseNamespace\x12\x16\n" +
	"\x06values\x18\x06 \x01(\tR\x06values\"\x96\x01\n" +
	"\vChartSource\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x12\n" +
	"\x04repo\x18\x02 \x01(\tR\x04repo\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\x12\x16\n" +
	"\x06sha256\x18\x05 \x01(\tR\x06sha256\x12\x19\n" +
	"\bhas_blob\x18\x06 \x01(\bR\ahasBlob\"B\n" +
	"\x10PluginCommandAck\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\xd8\x01\n" +
	"\x10LogsStartRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x10\n" +
	"\x03pod\x18\x02 \x01(\tR\x03pod\x12\x1c\n" +
	"\tcontainer\x18\x03 \x01(\tR\tcontainer\x12\x16\n" +
	"\x06follow\x18\x04 \x01(\bR\x06follow\x12\x1d\n" +
	"\n" +
	"tail_lines\x18\x05 \x01(\x03R\ttailLines\x12#\n" +
	"\rsince_seconds\x18\x06 \x01(\x03R\fsinceSeconds\x12\x1a\n" +
	"\bprevious\x18\a \x01(\bR\bprevious\"\x1f\n" +
	"\tLogsChunk\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"\x1f\n" +
	"\aLogsEnd\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\"\xb4\x01\n" +
	"\x10ExecStartRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x10\n" +
	"\x03pod\x18\x02 \x01(\tR\x03pod\x12\x1c\n" +
	"\tcontainer\x18\x03 \x01(\tR\tcontainer\x12\x18\n" +
	"\acommand\x18\x04 \x03(\tR\acommand\x12\x10\n" +
	"\x03tty\x18\x05 \x01(\bR\x03tty\x12\x12\n" +
	"\x04cols\x18\x06 \x01(\rR\x04cols\x12\x12\n" +
	"\x04rows\x18\a \x01(\rR\x04rows\"\x1f\n" +
	"\tExecStdin\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"4\n" +
	"\n" +
	"ExecResize\x12\x12\n" +
	"\x04cols\x18\x01 \x01(\rR\x04cols\x12\x12\n" +
	"\x04rows\x18\x02 \x01(\rR\x04rows\"8\n" +
	"\n" +
	"ExecOutput\x12\x16\n" +
	"\x06stream\x18\x01 \x01(\rR\x06stream\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"<\n" +
	"\aExecEnd\x12\x1b\n" +
	"\texit_code\x18\x01 \x01(\x05R\bexitCode\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"R\n" +
	"\x0eWSStartRequest\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12.\n" +
	"\aheaders\x18\x02 \x03(\v2\x14.pilot.v2.HTTPHeaderR\aheaders\"5\n" +
	"\aWSFrame\x12\x16\n" +
	"\x06opcode\x18\x01 \x01(\x05R\x06opcode\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"3\n" +
	"\x05WSEnd\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"\xaa\x02\n" +
	"\x10PluginStatusPush\x12\x19\n" +
	"\bcrd_name\x18\x01 \x01(\tR\acrdName\x12\x14\n" +
	"\x05phase\x18\x02 \x01(\tR\x05phase\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12)\n" +
	"\x10observed_version\x18\x04 \x01(\tR\x0fobservedVersion\x120\n" +
	"\x14observed_values_hash\x18\x05 \x01(\tR\x12observedValuesHash\x12#\n" +
	"\rhelm_revision\x18\x06 \x01(\x05R\fhelmRevision\x12!\n" +
	"\finstalled_at\x18\a \x01(\x03R\vinstalledAt\x12&\n" +
	"\x0flast_updated_at\x18\b \x01(\x03R\rlastUpdatedAt\"k\n" +
	"\x0ePluginLogChunk\x12\x19\n" +
	"\bcrd_name\x18\x01 \x01(\tR\acrdName\x12\x14\n" +
	"\x05level\x18\x02 \x01(\tR\x05level\x12\x0e\n" +
	"\x02ts\x18\x03 \x01(\x03R\x02ts\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\"]\n" +
	"\fPluginLogEnd\x12\x19\n" +
	"\bcrd_name\x18\x01 \x01(\tR\acrdName\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x18\n" +
	"\asummary\x18\x03 \x01(\tR\asummary*\x80\x02\n" +
	"\n" +
	"StreamKind\x12\x12\n" +
	"\x0eSTREAM_UNKNOWN\x10\x00\x12\x13\n" +
	"\x0fSTREAM_REGISTER\x10\x01\x12\x1b\n" +
	"\x17STREAM_RESOURCE_REQUEST\x10\n" +
	"\x12\x17\n" +
	"\x13STREAM_HTTP_REQUEST\x10\v\x12\x19\n" +
	"\x15STREAM_PLUGIN_COMMAND\x10\f\x12\x13\n" +
	"\x0fSTREAM_POD_LOGS\x10\r\x12\x13\n" +
	"\x0fSTREAM_POD_EXEC\x10\x0e\x12\x13\n" +
	"\x0fSTREAM_WS_PROXY\x10\x0f\x12\x1d\n" +
	"\x19STREAM_PLUGIN_STATUS_PUSH\x10\x14\x12\x1a\n" +
	"\x16STREAM_PLUGIN_LOG_PUSH\x10\x15B8Z6github.com/togettoyou/kpilot/pkg/common/proto/v2;protob\x06proto3"

var (
	file_v2_pilot_proto_rawDescOnce sync.Once
	file_v2_pilot_proto_rawDescData []byte
)

func file_v2_pilot_proto_rawDescGZIP() []byte {
	file_v2_pilot_proto_rawDescOnce.Do(func() {
		file_v2_pilot_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v2_pilot_proto_rawDesc), len(file_v2_pilot_proto_rawDesc)))
	})
	return file_v2_pilot_proto_rawDescData
}

var file_v2_pilot_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_v2_pilot_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_v2_pilot_proto_goTypes = []any{
	(StreamKind)(0),           // 0: pilot.v2.StreamKind
	(*StreamHeader)(nil),      // 1: pilot.v2.StreamHeader
	(*RegisterRequest)(nil),   // 2: pilot.v2.RegisterRequest
	(*RegisterAck)(nil),       // 3: pilot.v2.RegisterAck
	(*ResourceRequest)(nil),   // 4: pilot.v2.ResourceRequest
	(*ResourceResponse)(nil),  // 5: pilot.v2.ResourceResponse
	(*HTTPHeader)(nil),        // 6: pilot.v2.HTTPHeader
	(*HTTPRequestStart)(nil),  // 7: pilot.v2.HTTPRequestStart
	(*HTTPResponseStart)(nil), // 8: pilot.v2.HTTPResponseStart
	(*PluginCommand)(nil),     // 9: pilot.v2.PluginCommand
	(*PluginSpec)(nil),        // 10: pilot.v2.PluginSpec
	(*ChartSource)(nil),       // 11: pilot.v2.ChartSource
	(*PluginCommandAck)(nil),  // 12: pilot.v2.PluginCommandAck
	(*LogsStartRequest)(nil),  // 13: pilot.v2.LogsStartRequest
	(*LogsChunk)(nil),         // 14: pilot.v2.LogsChunk
	(*LogsEnd)(nil),           // 15: pilot.v2.LogsEnd
	(*ExecStartRequest)(nil),  // 16: pilot.v2.ExecStartRequest
	(*ExecStdin)(nil),         // 17: pilot.v2.ExecStdin
	(*ExecResize)(nil),        // 18: pilot.v2.ExecResize
	(*ExecOutput)(nil),        // 19: pilot.v2.ExecOutput
	(*ExecEnd)(nil),           // 20: pilot.v2.ExecEnd
	(*WSStartRequest)(nil),    // 21: pilot.v2.WSStartRequest
	(*WSFrame)(nil),           // 22: pilot.v2.WSFrame
	(*WSEnd)(nil),             // 23: pilot.v2.WSEnd
	(*PluginStatusPush)(nil),  // 24: pilot.v2.PluginStatusPush
	(*PluginLogChunk)(nil),    // 25: pilot.v2.PluginLogChunk
	(*PluginLogEnd)(nil),      // 26: pilot.v2.PluginLogEnd
}
var file_v2_pilot_proto_depIdxs = []int32{
	0,  // 0: pilot.v2.StreamHeader.kind:type_name -> pilot.v2.StreamKind
	6,  // 1: pilot.v2.HTTPRequestStart.headers:type_name -> pilot.v2.HTTPHeader
	6,  // 2: pilot.v2.HTTPResponseStart.headers:type_name -> pilot.v2.HTTPHeader
	10, // 3: pilot.v2.PluginCommand.spec:type_name -> pilot.v2.PluginSpec
	11, // 4: pilot.v2.PluginSpec.chart:type_name -> pilot.v2.ChartSource
	6,  // 5: pilot.v2.WSStartRequest.headers:type_name -> pilot.v2.HTTPHeader
	6,  // [6:6] is the sub-list for method output_type
	6,  // [6:6] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_v2_pilot_proto_init() }
func file_v2_pilot_proto_init() {
	if File_v2_pilot_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v2_pilot_proto_rawDesc), len(file_v2_pilot_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v2_pilot_proto_goTypes,
		DependencyIndexes: file_v2_pilot_proto_depIdxs,
		EnumInfos:         file_v2_pilot_proto_enumTypes,
		MessageInfos:      file_v2_pilot_proto_msgTypes,
	}.Build()
	File_v2_pilot_proto = out.File
	file_v2_pilot_proto_goTypes = nil
	file_v2_pilot_proto_depIdxs = nil
}
