// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: pilot.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PilotService_Connect_FullMethodName = "/pilot.v1.PilotService/Connect"
)

// PilotServiceClient is the client API for PilotService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PilotServiceClient interface {
	// Worker 主动连接 Server，建立双向流
	Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[WorkerMessage, ServerMessage], error)
}

type pilotServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPilotServiceClient(cc grpc.ClientConnInterface) PilotServiceClient {
	return &pilotServiceClient{cc}
}

func (c *pilotServiceClient) Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[WorkerMessage, ServerMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PilotService_ServiceDesc.Streams[0], PilotService_Connect_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WorkerMessage, ServerMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PilotService_ConnectClient = grpc.BidiStreamingClient[WorkerMessage, ServerMessage]

// PilotServiceServer is the server API for PilotService service.
// All implementations must embed UnimplementedPilotServiceServer
// for forward compatibility.
type PilotServiceServer interface {
	// Worker 主动连接 Server，建立双向流
	Connect(grpc.BidiStreamingServer[WorkerMessage, ServerMessage]) error
	mustEmbedUnimplementedPilotServiceServer()
}

// UnimplementedPilotServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPilotServiceServer struct{}

func (UnimplementedPilotServiceServer) Connect(grpc.BidiStreamingServer[WorkerMessage, ServerMessage]) error {
	return status.Error(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedPilotServiceServer) mustEmbedUnimplementedPilotServiceServer() {}
func (UnimplementedPilotServiceServer) testEmbeddedByValue()                      {}

// UnsafePilotServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PilotServiceServer will
// result in compilation errors.
type UnsafePilotServiceServer interface {
	mustEmbedUnimplementedPilotServiceServer()
}

func RegisterPilotServiceServer(s grpc.ServiceRegistrar, srv PilotServiceServer) {
	// If the following call panics, it indicates UnimplementedPilotServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PilotService_ServiceDesc, srv)
}

func _PilotService_Connect_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PilotServiceServer).Connect(&grpc.GenericServerStream[WorkerMessage, ServerMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PilotService_ConnectServer = grpc.BidiStreamingServer[WorkerMessage, ServerMessage]

// PilotService_ServiceDesc is the grpc.ServiceDesc for PilotService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PilotService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pilot.v1.PilotService",
	HandlerType: (*PilotServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Connect",
			Handler:       _PilotService_Connect_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "pilot.proto",
}
