// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: pilot.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WorkerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Empty for one-off pushes (PluginStatusPush, Heartbeat).
	// For *Start / BodyChunk / BodyEnd: routing key; receiver dispatches
	// chunks to the accumulator opened by the preceding *Start.
	// For Logs/Exec/WS: session_id (stable across all messages of the same session).
	RequestId string `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*WorkerMessage_Register
	//	*WorkerMessage_Heartbeat
	//	*WorkerMessage_ResourceRespStart
	//	*WorkerMessage_PluginStatus
	//	*WorkerMessage_PluginLog
	//	*WorkerMessage_PluginLogEnd
	//	*WorkerMessage_LogsChunk
	//	*WorkerMessage_LogsEnd
	//	*WorkerMessage_ExecOutput
	//	*WorkerMessage_ExecEnd
	//	*WorkerMessage_HttpRespStart
	//	*WorkerMessage_WsFrameRecv
	//	*WorkerMessage_WsEndRecv
	//	*WorkerMessage_BodyChunk
	//	*WorkerMessage_BodyEnd
	Payload       isWorkerMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkerMessage) Reset() {
	*x = WorkerMessage{}
	mi := &file_pilot_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerMessage) ProtoMessage() {}

func (x *WorkerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pilot_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerMessage.ProtoReflect.Descriptor instead.
func (*WorkerMessage) Descriptor() ([]byte, []int) {
	return file_pilot_proto_rawDescGZIP(), []int{0}
}

func (x *WorkerMessage) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *WorkerMessage) GetPayload() isWorkerMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *WorkerMessage) GetRegister() *RegisterRequest {
	if x != nil {
		if x, ok := x.Payload.(*WorkerMessage_Register); ok {
			return x.Register
		}
	}
	return nil
}

func (x *WorkerMessage) GetHeartbeat() *HeartbeatRequest {
	if x != nil {
		if x, ok := x.Payload.(*WorkerMessage_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *WorkerMessage) GetResourceRespStart() *ResourceResponseStart {
	if x != nil {
		if x, ok := x.Payload.(*WorkerMessage_ResourceRespStart); ok {
			return x.ResourceRespStart
		}
	}
	return nil
}

func (x *WorkerMessage) GetPluginStatus() *PluginStatusPush {
	if x != nil {
		if x, ok := x.Payload.(*WorkerMessage_PluginStatus); ok {
			return x.PluginStatus
		}
	}
	return nil
}

func (x *WorkerMessage) GetPluginLog() *PluginLogChunk {
	if x != nil {
		if x, ok := x.Payload.(*WorkerMessage_PluginLog); ok {
			return x.PluginLog
		}
	}
	return nil
}

func (x *WorkerMessage) GetPluginLogEnd() *PluginLogEnd {
	if x != nil {
		if x, ok := x.Payload.(*WorkerMessage_PluginLogEnd); ok {
			return x.PluginLogEnd
		}
	}
	return nil
}

func (x *WorkerMessage) GetLogsChunk() *LogsChunk {
	if x != nil {
		if x, ok := x.Payload.(*WorkerMessage_LogsChunk); ok {
			return x.LogsChunk
		}
	}
	return nil
}

func (x *WorkerMessage) GetLogsEnd() *LogsEnd {
	if x != nil {
		if x, ok := x.Payload.(*WorkerMessage_LogsEnd); ok {
			return x.LogsEnd
		}
	}
	return nil
}

func (x *WorkerMessage) GetExecOutput() *ExecOutput {
	if x != nil {
		if x, ok := x.Payload.(*WorkerMessage_ExecOutput); ok {
			return x.ExecOutput
		}
	}
	return nil
}

func (x *WorkerMessage) GetExecEnd() *ExecEnd {
	if x != nil {
		if x, ok := x.Payload.(*WorkerMessage_ExecEnd); ok {
			return x.ExecEnd
		}
	}
	return nil
}

func (x *WorkerMessage) GetHttpRespStart() *HTTPResponseStart {
	if x != nil {
		if x, ok := x.Payload.(*WorkerMessage_HttpRespStart); ok {
			return x.HttpRespStart
		}
	}
	return nil
}

func (x *WorkerMessage) GetWsFrameRecv() *WSFrame {
	if x != nil {
		if x, ok := x.Payload.(*WorkerMessage_WsFrameRecv); ok {
			return x.WsFrameRecv
		}
	}
	return nil
}

func (x *WorkerMessage) GetWsEndRecv() *WSEnd {
	if x != nil {
		if x, ok := x.Payload.(*WorkerMessage_WsEndRecv); ok {
			return x.WsEndRecv
		}
	}
	return nil
}

func (x *WorkerMessage) GetBodyChunk() *BodyChunk {
	if x != nil {
		if x, ok := x.Payload.(*WorkerMessage_BodyChunk); ok {
			return x.BodyChunk
		}
	}
	return nil
}

func (x *WorkerMessage) GetBodyEnd() *BodyEnd {
	if x != nil {
		if x, ok := x.Payload.(*WorkerMessage_BodyEnd); ok {
			return x.BodyEnd
		}
	}
	return nil
}

type isWorkerMessage_Payload interface {
	isWorkerMessage_Payload()
}

type WorkerMessage_Register struct {
	Register *RegisterRequest `protobuf:"bytes,10,opt,name=register,proto3,oneof"`
}

type WorkerMessage_Heartbeat struct {
	Heartbeat *HeartbeatRequest `protobuf:"bytes,11,opt,name=heartbeat,proto3,oneof"`
}

type WorkerMessage_ResourceRespStart struct {
	// tag 20 reserved — was NodeListPush.
	// tag 30 reserved — was unary ResourceResponse with bytes data.
	ResourceRespStart *ResourceResponseStart `protobuf:"bytes,31,opt,name=resource_resp_start,json=resourceRespStart,proto3,oneof"`
}

type WorkerMessage_PluginStatus struct {
	PluginStatus *PluginStatusPush `protobuf:"bytes,40,opt,name=plugin_status,json=pluginStatus,proto3,oneof"`
}

type WorkerMessage_PluginLog struct {
	// Plugin install / upgrade log streaming. Worker pushes one chunk
	// per Helm log line + key reconciler milestones; PluginLogEnd
	// closes the session and carries the final outcome.
	PluginLog *PluginLogChunk `protobuf:"bytes,41,opt,name=plugin_log,json=pluginLog,proto3,oneof"`
}

type WorkerMessage_PluginLogEnd struct {
	PluginLogEnd *PluginLogEnd `protobuf:"bytes,42,opt,name=plugin_log_end,json=pluginLogEnd,proto3,oneof"`
}

type WorkerMessage_LogsChunk struct {
	// Streaming sessions (logs / exec)
	LogsChunk *LogsChunk `protobuf:"bytes,50,opt,name=logs_chunk,json=logsChunk,proto3,oneof"`
}

type WorkerMessage_LogsEnd struct {
	LogsEnd *LogsEnd `protobuf:"bytes,51,opt,name=logs_end,json=logsEnd,proto3,oneof"`
}

type WorkerMessage_ExecOutput struct {
	ExecOutput *ExecOutput `protobuf:"bytes,60,opt,name=exec_output,json=execOutput,proto3,oneof"`
}

type WorkerMessage_ExecEnd struct {
	ExecEnd *ExecEnd `protobuf:"bytes,61,opt,name=exec_end,json=execEnd,proto3,oneof"`
}

type WorkerMessage_HttpRespStart struct {
	// tag 70 reserved — was unary HTTPResponse with bytes body.
	HttpRespStart *HTTPResponseStart `protobuf:"bytes,71,opt,name=http_resp_start,json=httpRespStart,proto3,oneof"`
}

type WorkerMessage_WsFrameRecv struct {
	// Reverse-proxy WebSocket (bidirectional streaming session).
	WsFrameRecv *WSFrame `protobuf:"bytes,80,opt,name=ws_frame_recv,json=wsFrameRecv,proto3,oneof"`
}

type WorkerMessage_WsEndRecv struct {
	WsEndRecv *WSEnd `protobuf:"bytes,81,opt,name=ws_end_recv,json=wsEndRecv,proto3,oneof"`
}

type WorkerMessage_BodyChunk struct {
	// Generic body streaming frames. Dispatched per request_id to the
	// accumulator previously opened by *Start (HTTP response body or
	// ResourceResponse data — receiver knows which from the *Start kind).
	BodyChunk *BodyChunk `protobuf:"bytes,90,opt,name=body_chunk,json=bodyChunk,proto3,oneof"`
}

type WorkerMessage_BodyEnd struct {
	BodyEnd *BodyEnd `protobuf:"bytes,91,opt,name=body_end,json=bodyEnd,proto3,oneof"`
}

func (*WorkerMessage_Register) isWorkerMessage_Payload() {}

func (*WorkerMessage_Heartbeat) isWorkerMessage_Payload() {}

func (*WorkerMessage_ResourceRespStart) isWorkerMessage_Payload() {}

func (*WorkerMessage_PluginStatus) isWorkerMessage_Payload() {}

func (*WorkerMessage_PluginLog) isWorkerMessage_Payload() {}

func (*WorkerMessage_PluginLogEnd) isWorkerMessage_Payload() {}

func (*WorkerMessage_LogsChunk) isWorkerMessage_Payload() {}

func (*WorkerMessage_LogsEnd) isWorkerMessage_Payload() {}

func (*WorkerMessage_ExecOutput) isWorkerMessage_Payload() {}

func (*WorkerMessage_ExecEnd) isWorkerMessage_Payload() {}

func (*WorkerMessage_HttpRespStart) isWorkerMessage_Payload() {}

func (*WorkerMessage_WsFrameRecv) isWorkerMessage_Payload() {}

func (*WorkerMessage_WsEndRecv) isWorkerMessage_Payload() {}

func (*WorkerMessage_BodyChunk) isWorkerMessage_Payload() {}

func (*WorkerMessage_BodyEnd) isWorkerMessage_Payload() {}

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClusterToken  string                 `protobuf:"bytes,1,opt,name=cluster_token,json=clusterToken,proto3" json:"cluster_token,omitempty"`
	WorkerVersion string                 `protobuf:"bytes,2,opt,name=worker_version,json=workerVersion,proto3" json:"worker_version,omitempty"`
	// K8s in-cluster DNS suffix (defaults to "cluster.local" CoreDNS-style;
	// clusters with a custom kubelet --cluster-domain need this). Used by
	// Server's reverse proxy to build FQDNs for in-cluster Service URLs —
	// short ".svc" form fails when Worker pod's resolv.conf doesn't include
	// the matching search domain.
	ClusterDomain string `protobuf:"bytes,3,opt,name=cluster_domain,json=clusterDomain,proto3" json:"cluster_domain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_pilot_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pilot_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_pilot_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterRequest) GetClusterToken() string {
	if x != nil {
		return x.ClusterToken
	}
	return ""
}

func (x *RegisterRequest) GetWorkerVersion() string {
	if x != nil {
		return x.WorkerVersion
	}
	return ""
}

func (x *RegisterRequest) GetClusterDomain() string {
	if x != nil {
		return x.ClusterDomain
	}
	return ""
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // unix seconds
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_pilot_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pilot_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_pilot_proto_rawDescGZIP(), []int{2}
}

func (x *HeartbeatRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// ResourceResponseStart opens a chunked ResourceResponse — receiver collects
// subsequent BodyChunk frames into the data buffer and finalizes on BodyEnd.
// For empty responses (delete, apply-with-no-return), send Start + BodyEnd
// with zero chunks. For error responses, set error and send Start + BodyEnd
// with zero chunks.
type ResourceResponseStart struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceResponseStart) Reset() {
	*x = ResourceResponseStart{}
	mi := &file_pilot_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceResponseStart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceResponseStart) ProtoMessage() {}

func (x *ResourceResponseStart) ProtoReflect() protoreflect.Message {
	mi := &file_pilot_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceResponseStart.ProtoReflect.Descriptor instead.
func (*ResourceResponseStart) Descriptor() ([]byte, []int) {
	return file_pilot_proto_rawDescGZIP(), []int{3}
}

func (x *ResourceResponseStart) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ResourceResponseStart) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type PluginStatusPush struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The CRD metadata.name (matches the registry plugin's name).
	CrdName string `protobuf:"bytes,1,opt,name=crd_name,json=crdName,proto3" json:"crd_name,omitempty"`
	// Pending / Installing / Running / Upgrading / Failed / Uninstalling
	Phase   string `protobuf:"bytes,2,opt,name=phase,proto3" json:"phase,omitempty"`
	Message string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	// Helm release version actually installed (from chart, not the CRD spec).
	ObservedVersion string `protobuf:"bytes,4,opt,name=observed_version,json=observedVersion,proto3" json:"observed_version,omitempty"`
	// sha256 of the values YAML actually applied — Server uses this to detect
	// drift between the registered values and what's running.
	ObservedValuesHash string `protobuf:"bytes,5,opt,name=observed_values_hash,json=observedValuesHash,proto3" json:"observed_values_hash,omitempty"`
	HelmRevision       int32  `protobuf:"varint,6,opt,name=helm_revision,json=helmRevision,proto3" json:"helm_revision,omitempty"`
	InstalledAt        int64  `protobuf:"varint,7,opt,name=installed_at,json=installedAt,proto3" json:"installed_at,omitempty"`         // unix seconds, 0 if not installed
	LastUpdatedAt      int64  `protobuf:"varint,8,opt,name=last_updated_at,json=lastUpdatedAt,proto3" json:"last_updated_at,omitempty"` // unix seconds
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *PluginStatusPush) Reset() {
	*x = PluginStatusPush{}
	mi := &file_pilot_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginStatusPush) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginStatusPush) ProtoMessage() {}

func (x *PluginStatusPush) ProtoReflect() protoreflect.Message {
	mi := &file_pilot_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginStatusPush.ProtoReflect.Descriptor instead.
func (*PluginStatusPush) Descriptor() ([]byte, []int) {
	return file_pilot_proto_rawDescGZIP(), []int{4}
}

func (x *PluginStatusPush) GetCrdName() string {
	if x != nil {
		return x.CrdName
	}
	return ""
}

func (x *PluginStatusPush) GetPhase() string {
	if x != nil {
		return x.Phase
	}
	return ""
}

func (x *PluginStatusPush) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *PluginStatusPush) GetObservedVersion() string {
	if x != nil {
		return x.ObservedVersion
	}
	return ""
}

func (x *PluginStatusPush) GetObservedValuesHash() string {
	if x != nil {
		return x.ObservedValuesHash
	}
	return ""
}

func (x *PluginStatusPush) GetHelmRevision() int32 {
	if x != nil {
		return x.HelmRevision
	}
	return 0
}

func (x *PluginStatusPush) GetInstalledAt() int64 {
	if x != nil {
		return x.InstalledAt
	}
	return 0
}

func (x *PluginStatusPush) GetLastUpdatedAt() int64 {
	if x != nil {
		return x.LastUpdatedAt
	}
	return 0
}

// PluginLogChunk carries a single progress line from a running install
// / upgrade / uninstall. Emitted both by the Helm SDK's own logger and
// by reconciler milestones around it. Frontend renders these in
// real time so the user can see WHY a long-running install is stuck.
type PluginLogChunk struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Matches PluginStatusPush.crd_name.
	CrdName string `protobuf:"bytes,1,opt,name=crd_name,json=crdName,proto3" json:"crd_name,omitempty"`
	// "info" / "warn" / "error". Worker classifies; frontend colorizes.
	Level string `protobuf:"bytes,2,opt,name=level,proto3" json:"level,omitempty"`
	// Unix milliseconds when the line was generated.
	Ts int64 `protobuf:"varint,3,opt,name=ts,proto3" json:"ts,omitempty"`
	// Single line of progress text. Worker is responsible for not
	// emitting secrets / values content; helm SDK output is safe.
	Message       string `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginLogChunk) Reset() {
	*x = PluginLogChunk{}
	mi := &file_pilot_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginLogChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginLogChunk) ProtoMessage() {}

func (x *PluginLogChunk) ProtoReflect() protoreflect.Message {
	mi := &file_pilot_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginLogChunk.ProtoReflect.Descriptor instead.
func (*PluginLogChunk) Descriptor() ([]byte, []int) {
	return file_pilot_proto_rawDescGZIP(), []int{5}
}

func (x *PluginLogChunk) GetCrdName() string {
	if x != nil {
		return x.CrdName
	}
	return ""
}

func (x *PluginLogChunk) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *PluginLogChunk) GetTs() int64 {
	if x != nil {
		return x.Ts
	}
	return 0
}

func (x *PluginLogChunk) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// PluginLogEnd terminates a log session.
type PluginLogEnd struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	CrdName string                 `protobuf:"bytes,1,opt,name=crd_name,json=crdName,proto3" json:"crd_name,omitempty"`
	Success bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	// Optional one-line summary ("installed v1.14.2 at rev 1",
	// "failed: timeout waiting for Deployment grafana"). Frontend
	// shows this in the terminal-state banner.
	Summary       string `protobuf:"bytes,3,opt,name=summary,proto3" json:"summary,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginLogEnd) Reset() {
	*x = PluginLogEnd{}
	mi := &file_pilot_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginLogEnd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginLogEnd) ProtoMessage() {}

func (x *PluginLogEnd) ProtoReflect() protoreflect.Message {
	mi := &file_pilot_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginLogEnd.ProtoReflect.Descriptor instead.
func (*PluginLogEnd) Descriptor() ([]byte, []int) {
	return file_pilot_proto_rawDescGZIP(), []int{6}
}

func (x *PluginLogEnd) GetCrdName() string {
	if x != nil {
		return x.CrdName
	}
	return ""
}

func (x *PluginLogEnd) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PluginLogEnd) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

type ServerMessage struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	RequestId string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ServerMessage_RegisterAck
	//	*ServerMessage_ResourceReqStart
	//	*ServerMessage_PluginCmdStart
	//	*ServerMessage_LogsStart
	//	*ServerMessage_LogsCancel
	//	*ServerMessage_ExecStart
	//	*ServerMessage_ExecStdin
	//	*ServerMessage_ExecResize
	//	*ServerMessage_ExecCancel
	//	*ServerMessage_HttpReqStart
	//	*ServerMessage_WsStart
	//	*ServerMessage_WsFrameSend
	//	*ServerMessage_WsEndSend
	//	*ServerMessage_BodyChunk
	//	*ServerMessage_BodyEnd
	Payload       isServerMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerMessage) Reset() {
	*x = ServerMessage{}
	mi := &file_pilot_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMessage) ProtoMessage() {}

func (x *ServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pilot_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMessage.ProtoReflect.Descriptor instead.
func (*ServerMessage) Descriptor() ([]byte, []int) {
	return file_pilot_proto_rawDescGZIP(), []int{7}
}

func (x *ServerMessage) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ServerMessage) GetPayload() isServerMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ServerMessage) GetRegisterAck() *RegisterAck {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_RegisterAck); ok {
			return x.RegisterAck
		}
	}
	return nil
}

func (x *ServerMessage) GetResourceReqStart() *ResourceRequestStart {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_ResourceReqStart); ok {
			return x.ResourceReqStart
		}
	}
	return nil
}

func (x *ServerMessage) GetPluginCmdStart() *PluginCommandStart {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_PluginCmdStart); ok {
			return x.PluginCmdStart
		}
	}
	return nil
}

func (x *ServerMessage) GetLogsStart() *LogsStartRequest {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_LogsStart); ok {
			return x.LogsStart
		}
	}
	return nil
}

func (x *ServerMessage) GetLogsCancel() *LogsCancelRequest {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_LogsCancel); ok {
			return x.LogsCancel
		}
	}
	return nil
}

func (x *ServerMessage) GetExecStart() *ExecStartRequest {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_ExecStart); ok {
			return x.ExecStart
		}
	}
	return nil
}

func (x *ServerMessage) GetExecStdin() *ExecStdin {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_ExecStdin); ok {
			return x.ExecStdin
		}
	}
	return nil
}

func (x *ServerMessage) GetExecResize() *ExecResize {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_ExecResize); ok {
			return x.ExecResize
		}
	}
	return nil
}

func (x *ServerMessage) GetExecCancel() *ExecCancelRequest {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_ExecCancel); ok {
			return x.ExecCancel
		}
	}
	return nil
}

func (x *ServerMessage) GetHttpReqStart() *HTTPRequestStart {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_HttpReqStart); ok {
			return x.HttpReqStart
		}
	}
	return nil
}

func (x *ServerMessage) GetWsStart() *WSStartRequest {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_WsStart); ok {
			return x.WsStart
		}
	}
	return nil
}

func (x *ServerMessage) GetWsFrameSend() *WSFrame {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_WsFrameSend); ok {
			return x.WsFrameSend
		}
	}
	return nil
}

func (x *ServerMessage) GetWsEndSend() *WSEnd {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_WsEndSend); ok {
			return x.WsEndSend
		}
	}
	return nil
}

func (x *ServerMessage) GetBodyChunk() *BodyChunk {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_BodyChunk); ok {
			return x.BodyChunk
		}
	}
	return nil
}

func (x *ServerMessage) GetBodyEnd() *BodyEnd {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_BodyEnd); ok {
			return x.BodyEnd
		}
	}
	return nil
}

type isServerMessage_Payload interface {
	isServerMessage_Payload()
}

type ServerMessage_RegisterAck struct {
	RegisterAck *RegisterAck `protobuf:"bytes,10,opt,name=register_ack,json=registerAck,proto3,oneof"`
}

type ServerMessage_ResourceReqStart struct {
	// tag 20 reserved — was unary ResourceRequest with bytes body.
	ResourceReqStart *ResourceRequestStart `protobuf:"bytes,21,opt,name=resource_req_start,json=resourceReqStart,proto3,oneof"`
}

type ServerMessage_PluginCmdStart struct {
	// tag 30 reserved — was unary PluginCommand with embedded chart blob.
	PluginCmdStart *PluginCommandStart `protobuf:"bytes,31,opt,name=plugin_cmd_start,json=pluginCmdStart,proto3,oneof"`
}

type ServerMessage_LogsStart struct {
	// Streaming sessions (logs / exec)
	LogsStart *LogsStartRequest `protobuf:"bytes,40,opt,name=logs_start,json=logsStart,proto3,oneof"`
}

type ServerMessage_LogsCancel struct {
	LogsCancel *LogsCancelRequest `protobuf:"bytes,41,opt,name=logs_cancel,json=logsCancel,proto3,oneof"`
}

type ServerMessage_ExecStart struct {
	ExecStart *ExecStartRequest `protobuf:"bytes,50,opt,name=exec_start,json=execStart,proto3,oneof"`
}

type ServerMessage_ExecStdin struct {
	ExecStdin *ExecStdin `protobuf:"bytes,51,opt,name=exec_stdin,json=execStdin,proto3,oneof"`
}

type ServerMessage_ExecResize struct {
	ExecResize *ExecResize `protobuf:"bytes,52,opt,name=exec_resize,json=execResize,proto3,oneof"`
}

type ServerMessage_ExecCancel struct {
	ExecCancel *ExecCancelRequest `protobuf:"bytes,53,opt,name=exec_cancel,json=execCancel,proto3,oneof"`
}

type ServerMessage_HttpReqStart struct {
	// tag 60 reserved — was unary HTTPRequest with bytes body.
	HttpReqStart *HTTPRequestStart `protobuf:"bytes,61,opt,name=http_req_start,json=httpReqStart,proto3,oneof"`
}

type ServerMessage_WsStart struct {
	// Reverse-proxy WebSocket.
	WsStart *WSStartRequest `protobuf:"bytes,70,opt,name=ws_start,json=wsStart,proto3,oneof"`
}

type ServerMessage_WsFrameSend struct {
	WsFrameSend *WSFrame `protobuf:"bytes,71,opt,name=ws_frame_send,json=wsFrameSend,proto3,oneof"`
}

type ServerMessage_WsEndSend struct {
	WsEndSend *WSEnd `protobuf:"bytes,72,opt,name=ws_end_send,json=wsEndSend,proto3,oneof"`
}

type ServerMessage_BodyChunk struct {
	// Generic body streaming frames. Dispatched per request_id to the
	// accumulator previously opened by *Start (HTTP request body,
	// ResourceRequest body, or PluginCommand chart blob — receiver knows
	// which from the *Start kind).
	BodyChunk *BodyChunk `protobuf:"bytes,90,opt,name=body_chunk,json=bodyChunk,proto3,oneof"`
}

type ServerMessage_BodyEnd struct {
	BodyEnd *BodyEnd `protobuf:"bytes,91,opt,name=body_end,json=bodyEnd,proto3,oneof"`
}

func (*ServerMessage_RegisterAck) isServerMessage_Payload() {}

func (*ServerMessage_ResourceReqStart) isServerMessage_Payload() {}

func (*ServerMessage_PluginCmdStart) isServerMessage_Payload() {}

func (*ServerMessage_LogsStart) isServerMessage_Payload() {}

func (*ServerMessage_LogsCancel) isServerMessage_Payload() {}

func (*ServerMessage_ExecStart) isServerMessage_Payload() {}

func (*ServerMessage_ExecStdin) isServerMessage_Payload() {}

func (*ServerMessage_ExecResize) isServerMessage_Payload() {}

func (*ServerMessage_ExecCancel) isServerMessage_Payload() {}

func (*ServerMessage_HttpReqStart) isServerMessage_Payload() {}

func (*ServerMessage_WsStart) isServerMessage_Payload() {}

func (*ServerMessage_WsFrameSend) isServerMessage_Payload() {}

func (*ServerMessage_WsEndSend) isServerMessage_Payload() {}

func (*ServerMessage_BodyChunk) isServerMessage_Payload() {}

func (*ServerMessage_BodyEnd) isServerMessage_Payload() {}

type RegisterAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ClusterId     string                 `protobuf:"bytes,2,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterAck) Reset() {
	*x = RegisterAck{}
	mi := &file_pilot_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterAck) ProtoMessage() {}

func (x *RegisterAck) ProtoReflect() protoreflect.Message {
	mi := &file_pilot_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterAck.ProtoReflect.Descriptor instead.
func (*RegisterAck) Descriptor() ([]byte, []int) {
	return file_pilot_proto_rawDescGZIP(), []int{8}
}

func (x *RegisterAck) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterAck) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *RegisterAck) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// ResourceRequestStart opens a chunked ResourceRequest. Same field set as the
// old ResourceRequest minus the body bytes — body (apply/update/patch JSON)
// flows in subsequent BodyChunk frames. Requests with no body (list/get/delete)
// still send BodyEnd with zero chunks to signal "ready to dispatch".
type ResourceRequestStart struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Action    string                 `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"` // list / get / apply / update / patch / delete / describe / list-full
	Group     string                 `protobuf:"bytes,2,opt,name=group,proto3" json:"group,omitempty"`
	Version   string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Kind      string                 `protobuf:"bytes,4,opt,name=kind,proto3" json:"kind,omitempty"`
	Namespace string                 `protobuf:"bytes,5,opt,name=namespace,proto3" json:"namespace,omitempty"` // empty = cluster-scoped
	Name      string                 `protobuf:"bytes,6,opt,name=name,proto3" json:"name,omitempty"`           // empty for list
	// list pagination: 0 = unbounded; non-empty continue_token = next page
	Limit         int64  `protobuf:"varint,7,opt,name=limit,proto3" json:"limit,omitempty"`
	ContinueToken string `protobuf:"bytes,8,opt,name=continue_token,json=continueToken,proto3" json:"continue_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceRequestStart) Reset() {
	*x = ResourceRequestStart{}
	mi := &file_pilot_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceRequestStart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceRequestStart) ProtoMessage() {}

func (x *ResourceRequestStart) ProtoReflect() protoreflect.Message {
	mi := &file_pilot_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceRequestStart.ProtoReflect.Descriptor instead.
func (*ResourceRequestStart) Descriptor() ([]byte, []int) {
	return file_pilot_proto_rawDescGZIP(), []int{9}
}

func (x *ResourceRequestStart) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *ResourceRequestStart) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *ResourceRequestStart) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ResourceRequestStart) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *ResourceRequestStart) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *ResourceRequestStart) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ResourceRequestStart) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ResourceRequestStart) GetContinueToken() string {
	if x != nil {
		return x.ContinueToken
	}
	return ""
}

// PluginCommandStart opens a PluginCommand. Chart blob (when ChartSourceMeta.
// has_blob is true) flows in subsequent BodyChunk frames; Worker collects
// + verifies sha256 + caches before dispatching.
type PluginCommandStart struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// "enable" → install or upgrade the Helm release driven by `spec`.
	// "disable" → uninstall the release; `spec` may be nil.
	Action string `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"`
	// CRD metadata.name — matches the registry plugin's name.
	CrdName string `protobuf:"bytes,2,opt,name=crd_name,json=crdName,proto3" json:"crd_name,omitempty"`
	// Only meaningful when action="enable". Server fills it from the registry
	// entry merged with the per-cluster overrides (values, version, namespace).
	Spec          *PluginSpec `protobuf:"bytes,3,opt,name=spec,proto3" json:"spec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginCommandStart) Reset() {
	*x = PluginCommandStart{}
	mi := &file_pilot_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginCommandStart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginCommandStart) ProtoMessage() {}

func (x *PluginCommandStart) ProtoReflect() protoreflect.Message {
	mi := &file_pilot_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginCommandStart.ProtoReflect.Descriptor instead.
func (*PluginCommandStart) Descriptor() ([]byte, []int) {
	return file_pilot_proto_rawDescGZIP(), []int{10}
}

func (x *PluginCommandStart) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *PluginCommandStart) GetCrdName() string {
	if x != nil {
		return x.CrdName
	}
	return ""
}

func (x *PluginCommandStart) GetSpec() *PluginSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

type PluginSpec struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Registry plugin id (PostgreSQL row id, for traceability — not required
	// by the reconciler, just useful in logs).
	PluginId         string       `protobuf:"bytes,1,opt,name=plugin_id,json=pluginId,proto3" json:"plugin_id,omitempty"`
	DisplayName      string       `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Chart            *ChartSource `protobuf:"bytes,3,opt,name=chart,proto3" json:"chart,omitempty"`
	ReleaseName      string       `protobuf:"bytes,4,opt,name=release_name,json=releaseName,proto3" json:"release_name,omitempty"`                // Helm release name
	ReleaseNamespace string       `protobuf:"bytes,5,opt,name=release_namespace,json=releaseNamespace,proto3" json:"release_namespace,omitempty"` // Helm release namespace (created if missing)
	Values           string       `protobuf:"bytes,6,opt,name=values,proto3" json:"values,omitempty"`                                             // YAML text (kept human-readable; not JSON)
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PluginSpec) Reset() {
	*x = PluginSpec{}
	mi := &file_pilot_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginSpec) ProtoMessage() {}

func (x *PluginSpec) ProtoReflect() protoreflect.Message {
	mi := &file_pilot_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginSpec.ProtoReflect.Descriptor instead.
func (*PluginSpec) Descriptor() ([]byte, []int) {
	return file_pilot_proto_rawDescGZIP(), []int{11}
}

func (x *PluginSpec) GetPluginId() string {
	if x != nil {
		return x.PluginId
	}
	return ""
}

func (x *PluginSpec) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *PluginSpec) GetChart() *ChartSource {
	if x != nil {
		return x.Chart
	}
	return nil
}

func (x *PluginSpec) GetReleaseName() string {
	if x != nil {
		return x.ReleaseName
	}
	return ""
}

func (x *PluginSpec) GetReleaseNamespace() string {
	if x != nil {
		return x.ReleaseNamespace
	}
	return ""
}

func (x *PluginSpec) GetValues() string {
	if x != nil {
		return x.Values
	}
	return ""
}

type ChartSource struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// "repo" → pulled by Helm from chart_repo at install time.
	// "local" → Worker reads from /var/lib/kpilot/charts/<sha256>.tgz which is
	// populated by streaming BodyChunk frames on the FIRST PluginCommand
	// referencing this sha. Subsequent commands with cached sha skip the
	// blob (has_blob = false).
	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	// type=repo
	Repo string `protobuf:"bytes,2,opt,name=repo,proto3" json:"repo,omitempty"`
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"` // chart name (both types)
	// Both types: for repo it's the Helm chart version; for local it's a
	// human-facing label (we identify the chart by sha256 internally).
	Version string `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	// type=local
	Sha256 string `protobuf:"bytes,5,opt,name=sha256,proto3" json:"sha256,omitempty"`
	// type=local: when true, BodyChunk + BodyEnd frames carry the .tgz bytes
	// following the PluginCommandStart. When false, Worker is expected to
	// have it cached on disk by sha256 (and will fall back to PluginStatusPush
	// "Failed: missing chart blob" if not, prompting Server to resend).
	HasBlob       bool `protobuf:"varint,6,opt,name=has_blob,json=hasBlob,proto3" json:"has_blob,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChartSource) Reset() {
	*x = ChartSource{}
	mi := &file_pilot_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChartSource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChartSource) ProtoMessage() {}

func (x *ChartSource) ProtoReflect() protoreflect.Message {
	mi := &file_pilot_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChartSource.ProtoReflect.Descriptor instead.
func (*ChartSource) Descriptor() ([]byte, []int) {
	return file_pilot_proto_rawDescGZIP(), []int{12}
}

func (x *ChartSource) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ChartSource) GetRepo() string {
	if x != nil {
		return x.Repo
	}
	return ""
}

func (x *ChartSource) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ChartSource) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ChartSource) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

func (x *ChartSource) GetHasBlob() bool {
	if x != nil {
		return x.HasBlob
	}
	return false
}

type LogsStartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Pod           string                 `protobuf:"bytes,2,opt,name=pod,proto3" json:"pod,omitempty"`
	Container     string                 `protobuf:"bytes,3,opt,name=container,proto3" json:"container,omitempty"` // empty = first/default container
	Follow        bool                   `protobuf:"varint,4,opt,name=follow,proto3" json:"follow,omitempty"`
	TailLines     int64                  `protobuf:"varint,5,opt,name=tail_lines,json=tailLines,proto3" json:"tail_lines,omitempty"`          // 0 = no tail limit
	SinceSeconds  int64                  `protobuf:"varint,6,opt,name=since_seconds,json=sinceSeconds,proto3" json:"since_seconds,omitempty"` // 0 = no time limit
	Previous      bool                   `protobuf:"varint,7,opt,name=previous,proto3" json:"previous,omitempty"`                             // logs from previous container instance
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogsStartRequest) Reset() {
	*x = LogsStartRequest{}
	mi := &file_pilot_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogsStartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogsStartRequest) ProtoMessage() {}

func (x *LogsStartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pilot_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogsStartRequest.ProtoReflect.Descriptor instead.
func (*LogsStartRequest) Descriptor() ([]byte, []int) {
	return file_pilot_proto_rawDescGZIP(), []int{13}
}

func (x *LogsStartRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *LogsStartRequest) GetPod() string {
	if x != nil {
		return x.Pod
	}
	return ""
}

func (x *LogsStartRequest) GetContainer() string {
	if x != nil {
		return x.Container
	}
	return ""
}

func (x *LogsStartRequest) GetFollow() bool {
	if x != nil {
		return x.Follow
	}
	return false
}

func (x *LogsStartRequest) GetTailLines() int64 {
	if x != nil {
		return x.TailLines
	}
	return 0
}

func (x *LogsStartRequest) GetSinceSeconds() int64 {
	if x != nil {
		return x.SinceSeconds
	}
	return 0
}

func (x *LogsStartRequest) GetPrevious() bool {
	if x != nil {
		return x.Previous
	}
	return false
}

type LogsCancelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogsCancelRequest) Reset() {
	*x = LogsCancelRequest{}
	mi := &file_pilot_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogsCancelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogsCancelRequest) ProtoMessage() {}

func (x *LogsCancelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pilot_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogsCancelRequest.ProtoReflect.Descriptor instead.
func (*LogsCancelRequest) Descriptor() ([]byte, []int) {
	return file_pilot_proto_rawDescGZIP(), []int{14}
}

type LogsChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogsChunk) Reset() {
	*x = LogsChunk{}
	mi := &file_pilot_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogsChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogsChunk) ProtoMessage() {}

func (x *LogsChunk) ProtoReflect() protoreflect.Message {
	mi := &file_pilot_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogsChunk.ProtoReflect.Descriptor instead.
func (*LogsChunk) Descriptor() ([]byte, []int) {
	return file_pilot_proto_rawDescGZIP(), []int{15}
}

func (x *LogsChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type LogsEnd struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"` // empty = clean EOF
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogsEnd) Reset() {
	*x = LogsEnd{}
	mi := &file_pilot_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogsEnd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogsEnd) ProtoMessage() {}

func (x *LogsEnd) ProtoReflect() protoreflect.Message {
	mi := &file_pilot_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogsEnd.ProtoReflect.Descriptor instead.
func (*LogsEnd) Descriptor() ([]byte, []int) {
	return file_pilot_proto_rawDescGZIP(), []int{16}
}

func (x *LogsEnd) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ExecStartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Pod           string                 `protobuf:"bytes,2,opt,name=pod,proto3" json:"pod,omitempty"`
	Container     string                 `protobuf:"bytes,3,opt,name=container,proto3" json:"container,omitempty"`
	Command       []string               `protobuf:"bytes,4,rep,name=command,proto3" json:"command,omitempty"`
	Tty           bool                   `protobuf:"varint,5,opt,name=tty,proto3" json:"tty,omitempty"`
	Cols          uint32                 `protobuf:"varint,6,opt,name=cols,proto3" json:"cols,omitempty"` // initial terminal size
	Rows          uint32                 `protobuf:"varint,7,opt,name=rows,proto3" json:"rows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecStartRequest) Reset() {
	*x = ExecStartRequest{}
	mi := &file_pilot_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecStartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecStartRequest) ProtoMessage() {}

func (x *ExecStartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pilot_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecStartRequest.ProtoReflect.Descriptor instead.
func (*ExecStartRequest) Descriptor() ([]byte, []int) {
	return file_pilot_proto_rawDescGZIP(), []int{17}
}

func (x *ExecStartRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *ExecStartRequest) GetPod() string {
	if x != nil {
		return x.Pod
	}
	return ""
}

func (x *ExecStartRequest) GetContainer() string {
	if x != nil {
		return x.Container
	}
	return ""
}

func (x *ExecStartRequest) GetCommand() []string {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *ExecStartRequest) GetTty() bool {
	if x != nil {
		return x.Tty
	}
	return false
}

func (x *ExecStartRequest) GetCols() uint32 {
	if x != nil {
		return x.Cols
	}
	return 0
}

func (x *ExecStartRequest) GetRows() uint32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

type ExecStdin struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecStdin) Reset() {
	*x = ExecStdin{}
	mi := &file_pilot_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecStdin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecStdin) ProtoMessage() {}

func (x *ExecStdin) ProtoReflect() protoreflect.Message {
	mi := &file_pilot_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecStdin.ProtoReflect.Descriptor instead.
func (*ExecStdin) Descriptor() ([]byte, []int) {
	return file_pilot_proto_rawDescGZIP(), []int{18}
}

func (x *ExecStdin) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type ExecResize struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cols          uint32                 `protobuf:"varint,1,opt,name=cols,proto3" json:"cols,omitempty"`
	Rows          uint32                 `protobuf:"varint,2,opt,name=rows,proto3" json:"rows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecResize) Reset() {
	*x = ExecResize{}
	mi := &file_pilot_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecResize) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecResize) ProtoMessage() {}

func (x *ExecResize) ProtoReflect() protoreflect.Message {
	mi := &file_pilot_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecResize.ProtoReflect.Descriptor instead.
func (*ExecResize) Descriptor() ([]byte, []int) {
	return file_pilot_proto_rawDescGZIP(), []int{19}
}

func (x *ExecResize) GetCols() uint32 {
	if x != nil {
		return x.Cols
	}
	return 0
}

func (x *ExecResize) GetRows() uint32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

type ExecCancelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecCancelRequest) Reset() {
	*x = ExecCancelRequest{}
	mi := &file_pilot_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecCancelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecCancelRequest) ProtoMessage() {}

func (x *ExecCancelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pilot_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecCancelRequest.ProtoReflect.Descriptor instead.
func (*ExecCancelRequest) Descriptor() ([]byte, []int) {
	return file_pilot_proto_rawDescGZIP(), []int{20}
}

type ExecOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stream        uint32                 `protobuf:"varint,1,opt,name=stream,proto3" json:"stream,omitempty"` // 1=stdout, 2=stderr
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecOutput) Reset() {
	*x = ExecOutput{}
	mi := &file_pilot_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecOutput) ProtoMessage() {}

func (x *ExecOutput) ProtoReflect() protoreflect.Message {
	mi := &file_pilot_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecOutput.ProtoReflect.Descriptor instead.
func (*ExecOutput) Descriptor() ([]byte, []int) {
	return file_pilot_proto_rawDescGZIP(), []int{21}
}

func (x *ExecOutput) GetStream() uint32 {
	if x != nil {
		return x.Stream
	}
	return 0
}

func (x *ExecOutput) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type ExecEnd struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExitCode      int32                  `protobuf:"varint,1,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecEnd) Reset() {
	*x = ExecEnd{}
	mi := &file_pilot_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecEnd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecEnd) ProtoMessage() {}

func (x *ExecEnd) ProtoReflect() protoreflect.Message {
	mi := &file_pilot_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecEnd.ProtoReflect.Descriptor instead.
func (*ExecEnd) Descriptor() ([]byte, []int) {
	return file_pilot_proto_rawDescGZIP(), []int{22}
}

func (x *ExecEnd) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *ExecEnd) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// HTTPHeader is one (Name, Value) pair. Repeated entries with the same name
// are allowed (e.g. Set-Cookie) and preserve order on the wire.
type HTTPHeader struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HTTPHeader) Reset() {
	*x = HTTPHeader{}
	mi := &file_pilot_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HTTPHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HTTPHeader) ProtoMessage() {}

func (x *HTTPHeader) ProtoReflect() protoreflect.Message {
	mi := &file_pilot_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HTTPHeader.ProtoReflect.Descriptor instead.
func (*HTTPHeader) Descriptor() ([]byte, []int) {
	return file_pilot_proto_rawDescGZIP(), []int{23}
}

func (x *HTTPHeader) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *HTTPHeader) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type HTTPRequestStart struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// HTTP method (GET / POST / PUT / DELETE / PATCH / HEAD / OPTIONS).
	Method string `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	// Absolute URL of the in-cluster Service the Worker should forward to.
	Url string `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	// Request headers (Host is rewritten by the Worker to match url's host).
	Headers       []*HTTPHeader `protobuf:"bytes,3,rep,name=headers,proto3" json:"headers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HTTPRequestStart) Reset() {
	*x = HTTPRequestStart{}
	mi := &file_pilot_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HTTPRequestStart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HTTPRequestStart) ProtoMessage() {}

func (x *HTTPRequestStart) ProtoReflect() protoreflect.Message {
	mi := &file_pilot_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HTTPRequestStart.ProtoReflect.Descriptor instead.
func (*HTTPRequestStart) Descriptor() ([]byte, []int) {
	return file_pilot_proto_rawDescGZIP(), []int{24}
}

func (x *HTTPRequestStart) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *HTTPRequestStart) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *HTTPRequestStart) GetHeaders() []*HTTPHeader {
	if x != nil {
		return x.Headers
	}
	return nil
}

type HTTPResponseStart struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Status code from the upstream Service. 502 if the Worker couldn't
	// reach the Service at all (DNS/connect/timeout); the `error` field
	// carries the underlying reason in that case.
	Status  int32         `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Headers []*HTTPHeader `protobuf:"bytes,2,rep,name=headers,proto3" json:"headers,omitempty"`
	// Empty on success (any HTTP status). Set when the Worker failed to
	// dispatch the request before it could read any body bytes. When set,
	// BodyEnd follows with zero chunks.
	Error         string `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HTTPResponseStart) Reset() {
	*x = HTTPResponseStart{}
	mi := &file_pilot_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HTTPResponseStart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HTTPResponseStart) ProtoMessage() {}

func (x *HTTPResponseStart) ProtoReflect() protoreflect.Message {
	mi := &file_pilot_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HTTPResponseStart.ProtoReflect.Descriptor instead.
func (*HTTPResponseStart) Descriptor() ([]byte, []int) {
	return file_pilot_proto_rawDescGZIP(), []int{25}
}

func (x *HTTPResponseStart) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *HTTPResponseStart) GetHeaders() []*HTTPHeader {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *HTTPResponseStart) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// BodyChunk carries a slice of body bytes for any of the chunked request /
// response kinds. Receiver dispatches per request_id to the accumulator
// opened by the matching *Start. Empty data on a BodyChunk is technically
// legal but senders avoid it.
type BodyChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BodyChunk) Reset() {
	*x = BodyChunk{}
	mi := &file_pilot_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BodyChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BodyChunk) ProtoMessage() {}

func (x *BodyChunk) ProtoReflect() protoreflect.Message {
	mi := &file_pilot_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BodyChunk.ProtoReflect.Descriptor instead.
func (*BodyChunk) Descriptor() ([]byte, []int) {
	return file_pilot_proto_rawDescGZIP(), []int{26}
}

func (x *BodyChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// BodyEnd terminates a chunked body stream. error is empty on clean EOF /
// successful completion; non-empty when the sender failed partway through
// reading the upstream body (e.g. upstream connection reset mid-response).
// Receiver should surface the error to the original caller in that case.
type BodyEnd struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BodyEnd) Reset() {
	*x = BodyEnd{}
	mi := &file_pilot_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BodyEnd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BodyEnd) ProtoMessage() {}

func (x *BodyEnd) ProtoReflect() protoreflect.Message {
	mi := &file_pilot_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BodyEnd.ProtoReflect.Descriptor instead.
func (*BodyEnd) Descriptor() ([]byte, []int) {
	return file_pilot_proto_rawDescGZIP(), []int{27}
}

func (x *BodyEnd) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type WSStartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Headers       []*HTTPHeader          `protobuf:"bytes,2,rep,name=headers,proto3" json:"headers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WSStartRequest) Reset() {
	*x = WSStartRequest{}
	mi := &file_pilot_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WSStartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WSStartRequest) ProtoMessage() {}

func (x *WSStartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pilot_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WSStartRequest.ProtoReflect.Descriptor instead.
func (*WSStartRequest) Descriptor() ([]byte, []int) {
	return file_pilot_proto_rawDescGZIP(), []int{28}
}

func (x *WSStartRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *WSStartRequest) GetHeaders() []*HTTPHeader {
	if x != nil {
		return x.Headers
	}
	return nil
}

type WSFrame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// RFC 6455 opcodes. We forward 1 (text), 2 (binary). Control frames
	// (close/ping/pong) are handled by the WS library on each leg.
	// Worker / Server split frames larger than wsMaxFrameBytes into multiple
	// WSFrame messages so a single Send stays small.
	Opcode        int32  `protobuf:"varint,1,opt,name=opcode,proto3" json:"opcode,omitempty"`
	Data          []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WSFrame) Reset() {
	*x = WSFrame{}
	mi := &file_pilot_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WSFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WSFrame) ProtoMessage() {}

func (x *WSFrame) ProtoReflect() protoreflect.Message {
	mi := &file_pilot_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WSFrame.ProtoReflect.Descriptor instead.
func (*WSFrame) Descriptor() ([]byte, []int) {
	return file_pilot_proto_rawDescGZIP(), []int{29}
}

func (x *WSFrame) GetOpcode() int32 {
	if x != nil {
		return x.Opcode
	}
	return 0
}

func (x *WSFrame) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type WSEnd struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WSEnd) Reset() {
	*x = WSEnd{}
	mi := &file_pilot_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WSEnd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WSEnd) ProtoMessage() {}

func (x *WSEnd) ProtoReflect() protoreflect.Message {
	mi := &file_pilot_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WSEnd.ProtoReflect.Descriptor instead.
func (*WSEnd) Descriptor() ([]byte, []int) {
	return file_pilot_proto_rawDescGZIP(), []int{30}
}

func (x *WSEnd) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *WSEnd) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_pilot_proto protoreflect.FileDescriptor

const file_pilot_proto_rawDesc = "" +
	"\n" +
	"\vpilot.proto\x12\bpilot.v1\"\xde\a\n" +
	"\rWorkerMessage\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x127\n" +
	"\bregister\x18\n" +
	" \x01(\v2\x19.pilot.v1.RegisterRequestH\x00R\bregister\x12:\n" +
	"\theartbeat\x18\v \x01(\v2\x1a.pilot.v1.HeartbeatRequestH\x00R\theartbeat\x12Q\n" +
	"\x13resource_resp_start\x18\x1f \x01(\v2\x1f.pilot.v1.ResourceResponseStartH\x00R\x11resourceRespStart\x12A\n" +
	"\rplugin_status\x18( \x01(\v2\x1a.pilot.v1.PluginStatusPushH\x00R\fpluginStatus\x129\n" +
	"\n" +
	"plugin_log\x18) \x01(\v2\x18.pilot.v1.PluginLogChunkH\x00R\tpluginLog\x12>\n" +
	"\x0eplugin_log_end\x18* \x01(\v2\x16.pilot.v1.PluginLogEndH\x00R\fpluginLogEnd\x124\n" +
	"\n" +
	"logs_chunk\x182 \x01(\v2\x13.pilot.v1.LogsChunkH\x00R\tlogsChunk\x12.\n" +
	"\blogs_end\x183 \x01(\v2\x11.pilot.v1.LogsEndH\x00R\alogsEnd\x127\n" +
	"\vexec_output\x18< \x01(\v2\x14.pilot.v1.ExecOutputH\x00R\n" +
	"execOutput\x12.\n" +
	"\bexec_end\x18= \x01(\v2\x11.pilot.v1.ExecEndH\x00R\aexecEnd\x12E\n" +
	"\x0fhttp_resp_start\x18G \x01(\v2\x1b.pilot.v1.HTTPResponseStartH\x00R\rhttpRespStart\x127\n" +
	"\rws_frame_recv\x18P \x01(\v2\x11.pilot.v1.WSFrameH\x00R\vwsFrameRecv\x121\n" +
	"\vws_end_recv\x18Q \x01(\v2\x0f.pilot.v1.WSEndH\x00R\twsEndRecv\x124\n" +
	"\n" +
	"body_chunk\x18Z \x01(\v2\x13.pilot.v1.BodyChunkH\x00R\tbodyChunk\x12.\n" +
	"\bbody_end\x18[ \x01(\v2\x11.pilot.v1.BodyEndH\x00R\abodyEndB\t\n" +
	"\apayloadJ\x04\b\x14\x10\x15J\x04\b\x1e\x10\x1fJ\x04\bF\x10GR\tnode_listR\rresource_respR\thttp_resp\"\x84\x01\n" +
	"\x0fRegisterRequest\x12#\n" +
	"\rcluster_token\x18\x01 \x01(\tR\fclusterToken\x12%\n" +
	"\x0eworker_version\x18\x02 \x01(\tR\rworkerVersion\x12%\n" +
	"\x0ecluster_domain\x18\x03 \x01(\tR\rclusterDomain\"0\n" +
	"\x10HeartbeatRequest\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\"G\n" +
	"\x15ResourceResponseStart\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\xaa\x02\n" +
	"\x10PluginStatusPush\x12\x19\n" +
	"\bcrd_name\x18\x01 \x01(\tR\acrdName\x12\x14\n" +
	"\x05phase\x18\x02 \x01(\tR\x05phase\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12)\n" +
	"\x10observed_version\x18\x04 \x01(\tR\x0fobservedVersion\x120\n" +
	"\x14observed_values_hash\x18\x05 \x01(\tR\x12observedValuesHash\x12#\n" +
	"\rhelm_revision\x18\x06 \x01(\x05R\fhelmRevision\x12!\n" +
	"\finstalled_at\x18\a \x01(\x03R\vinstalledAt\x12&\n" +
	"\x0flast_updated_at\x18\b \x01(\x03R\rlastUpdatedAt\"k\n" +
	"\x0ePluginLogChunk\x12\x19\n" +
	"\bcrd_name\x18\x01 \x01(\tR\acrdName\x12\x14\n" +
	"\x05level\x18\x02 \x01(\tR\x05level\x12\x0e\n" +
	"\x02ts\x18\x03 \x01(\x03R\x02ts\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\"]\n" +
	"\fPluginLogEnd\x12\x19\n" +
	"\bcrd_name\x18\x01 \x01(\tR\acrdName\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x18\n" +
	"\asummary\x18\x03 \x01(\tR\asummary\"\xfb\a\n" +
	"\rServerMessage\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12:\n" +
	"\fregister_ack\x18\n" +
	" \x01(\v2\x15.pilot.v1.RegisterAckH\x00R\vregisterAck\x12N\n" +
	"\x12resource_req_start\x18\x15 \x01(\v2\x1e.pilot.v1.ResourceRequestStartH\x00R\x10resourceReqStart\x12H\n" +
	"\x10plugin_cmd_start\x18\x1f \x01(\v2\x1c.pilot.v1.PluginCommandStartH\x00R\x0epluginCmdStart\x12;\n" +
	"\n" +
	"logs_start\x18( \x01(\v2\x1a.pilot.v1.LogsStartRequestH\x00R\tlogsStart\x12>\n" +
	"\vlogs_cancel\x18) \x01(\v2\x1b.pilot.v1.LogsCancelRequestH\x00R\n" +
	"logsCancel\x12;\n" +
	"\n" +
	"exec_start\x182 \x01(\v2\x1a.pilot.v1.ExecStartRequestH\x00R\texecStart\x124\n" +
	"\n" +
	"exec_stdin\x183 \x01(\v2\x13.pilot.v1.ExecStdinH\x00R\texecStdin\x127\n" +
	"\vexec_resize\x184 \x01(\v2\x14.pilot.v1.ExecResizeH\x00R\n" +
	"execResize\x12>\n" +
	"\vexec_cancel\x185 \x01(\v2\x1b.pilot.v1.ExecCancelRequestH\x00R\n" +
	"execCancel\x12B\n" +
	"\x0ehttp_req_start\x18= \x01(\v2\x1a.pilot.v1.HTTPRequestStartH\x00R\fhttpReqStart\x125\n" +
	"\bws_start\x18F \x01(\v2\x18.pilot.v1.WSStartRequestH\x00R\awsStart\x127\n" +
	"\rws_frame_send\x18G \x01(\v2\x11.pilot.v1.WSFrameH\x00R\vwsFrameSend\x121\n" +
	"\vws_end_send\x18H \x01(\v2\x0f.pilot.v1.WSEndH\x00R\twsEndSend\x124\n" +
	"\n" +
	"body_chunk\x18Z \x01(\v2\x13.pilot.v1.BodyChunkH\x00R\tbodyChunk\x12.\n" +
	"\bbody_end\x18[ \x01(\v2\x11.pilot.v1.BodyEndH\x00R\abodyEndB\t\n" +
	"\apayloadJ\x04\b\x14\x10\x15J\x04\b\x1e\x10\x1fJ\x04\b<\x10=R\fresource_reqR\n" +
	"plugin_cmdR\bhttp_req\"`\n" +
	"\vRegisterAck\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x02 \x01(\tR\tclusterId\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\xe1\x01\n" +
	"\x14ResourceRequestStart\x12\x16\n" +
	"\x06action\x18\x01 \x01(\tR\x06action\x12\x14\n" +
	"\x05group\x18\x02 \x01(\tR\x05group\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12\x12\n" +
	"\x04kind\x18\x04 \x01(\tR\x04kind\x12\x1c\n" +
	"\tnamespace\x18\x05 \x01(\tR\tnamespace\x12\x12\n" +
	"\x04name\x18\x06 \x01(\tR\x04name\x12\x14\n" +
	"\x05limit\x18\a \x01(\x03R\x05limit\x12%\n" +
	"\x0econtinue_token\x18\b \x01(\tR\rcontinueToken\"q\n" +
	"\x12PluginCommandStart\x12\x16\n" +
	"\x06action\x18\x01 \x01(\tR\x06action\x12\x19\n" +
	"\bcrd_name\x18\x02 \x01(\tR\acrdName\x12(\n" +
	"\x04spec\x18\x03 \x01(\v2\x14.pilot.v1.PluginSpecR\x04spec\"\xe1\x01\n" +
	"\n" +
	"PluginSpec\x12\x1b\n" +
	"\tplugin_id\x18\x01 \x01(\tR\bpluginId\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12+\n" +
	"\x05chart\x18\x03 \x01(\v2\x15.pilot.v1.ChartSourceR\x05chart\x12!\n" +
	"\frelease_name\x18\x04 \x01(\tR\vreleaseName\x12+\n" +
	"\x11release_namespace\x18\x05 \x01(\tR\x10releaseNamespace\x12\x16\n" +
	"\x06values\x18\x06 \x01(\tR\x06values\"\xa2\x01\n" +
	"\vChartSource\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x12\n" +
	"\x04repo\x18\x02 \x01(\tR\x04repo\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\x12\x16\n" +
	"\x06sha256\x18\x05 \x01(\tR\x06sha256\x12\x19\n" +
	"\bhas_blob\x18\x06 \x01(\bR\ahasBlobJ\x04\b\a\x10\bR\x04blob\"\xd8\x01\n" +
	"\x10LogsStartRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x10\n" +
	"\x03pod\x18\x02 \x01(\tR\x03pod\x12\x1c\n" +
	"\tcontainer\x18\x03 \x01(\tR\tcontainer\x12\x16\n" +
	"\x06follow\x18\x04 \x01(\bR\x06follow\x12\x1d\n" +
	"\n" +
	"tail_lines\x18\x05 \x01(\x03R\ttailLines\x12#\n" +
	"\rsince_seconds\x18\x06 \x01(\x03R\fsinceSeconds\x12\x1a\n" +
	"\bprevious\x18\a \x01(\bR\bprevious\"\x13\n" +
	"\x11LogsCancelRequest\"\x1f\n" +
	"\tLogsChunk\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"\x1f\n" +
	"\aLogsEnd\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\"\xb4\x01\n" +
	"\x10ExecStartRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x10\n" +
	"\x03pod\x18\x02 \x01(\tR\x03pod\x12\x1c\n" +
	"\tcontainer\x18\x03 \x01(\tR\tcontainer\x12\x18\n" +
	"\acommand\x18\x04 \x03(\tR\acommand\x12\x10\n" +
	"\x03tty\x18\x05 \x01(\bR\x03tty\x12\x12\n" +
	"\x04cols\x18\x06 \x01(\rR\x04cols\x12\x12\n" +
	"\x04rows\x18\a \x01(\rR\x04rows\"\x1f\n" +
	"\tExecStdin\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"4\n" +
	"\n" +
	"ExecResize\x12\x12\n" +
	"\x04cols\x18\x01 \x01(\rR\x04cols\x12\x12\n" +
	"\x04rows\x18\x02 \x01(\rR\x04rows\"\x13\n" +
	"\x11ExecCancelRequest\"8\n" +
	"\n" +
	"ExecOutput\x12\x16\n" +
	"\x06stream\x18\x01 \x01(\rR\x06stream\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"<\n" +
	"\aExecEnd\x12\x1b\n" +
	"\texit_code\x18\x01 \x01(\x05R\bexitCode\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"6\n" +
	"\n" +
	"HTTPHeader\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"l\n" +
	"\x10HTTPRequestStart\x12\x16\n" +
	"\x06method\x18\x01 \x01(\tR\x06method\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12.\n" +
	"\aheaders\x18\x03 \x03(\v2\x14.pilot.v1.HTTPHeaderR\aheaders\"q\n" +
	"\x11HTTPResponseStart\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x05R\x06status\x12.\n" +
	"\aheaders\x18\x02 \x03(\v2\x14.pilot.v1.HTTPHeaderR\aheaders\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"\x1f\n" +
	"\tBodyChunk\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"\x1f\n" +
	"\aBodyEnd\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\"R\n" +
	"\x0eWSStartRequest\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12.\n" +
	"\aheaders\x18\x02 \x03(\v2\x14.pilot.v1.HTTPHeaderR\aheaders\"5\n" +
	"\aWSFrame\x12\x16\n" +
	"\x06opcode\x18\x01 \x01(\x05R\x06opcode\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"3\n" +
	"\x05WSEnd\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason2O\n" +
	"\fPilotService\x12?\n" +
	"\aConnect\x12\x17.pilot.v1.WorkerMessage\x1a\x17.pilot.v1.ServerMessage(\x010\x01B5Z3github.com/togettoyou/kpilot/pkg/common/proto;protob\x06proto3"

var (
	file_pilot_proto_rawDescOnce sync.Once
	file_pilot_proto_rawDescData []byte
)

func file_pilot_proto_rawDescGZIP() []byte {
	file_pilot_proto_rawDescOnce.Do(func() {
		file_pilot_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pilot_proto_rawDesc), len(file_pilot_proto_rawDesc)))
	})
	return file_pilot_proto_rawDescData
}

var file_pilot_proto_msgTypes = make([]protoimpl.MessageInfo, 31)
var file_pilot_proto_goTypes = []any{
	(*WorkerMessage)(nil),         // 0: pilot.v1.WorkerMessage
	(*RegisterRequest)(nil),       // 1: pilot.v1.RegisterRequest
	(*HeartbeatRequest)(nil),      // 2: pilot.v1.HeartbeatRequest
	(*ResourceResponseStart)(nil), // 3: pilot.v1.ResourceResponseStart
	(*PluginStatusPush)(nil),      // 4: pilot.v1.PluginStatusPush
	(*PluginLogChunk)(nil),        // 5: pilot.v1.PluginLogChunk
	(*PluginLogEnd)(nil),          // 6: pilot.v1.PluginLogEnd
	(*ServerMessage)(nil),         // 7: pilot.v1.ServerMessage
	(*RegisterAck)(nil),           // 8: pilot.v1.RegisterAck
	(*ResourceRequestStart)(nil),  // 9: pilot.v1.ResourceRequestStart
	(*PluginCommandStart)(nil),    // 10: pilot.v1.PluginCommandStart
	(*PluginSpec)(nil),            // 11: pilot.v1.PluginSpec
	(*ChartSource)(nil),           // 12: pilot.v1.ChartSource
	(*LogsStartRequest)(nil),      // 13: pilot.v1.LogsStartRequest
	(*LogsCancelRequest)(nil),     // 14: pilot.v1.LogsCancelRequest
	(*LogsChunk)(nil),             // 15: pilot.v1.LogsChunk
	(*LogsEnd)(nil),               // 16: pilot.v1.LogsEnd
	(*ExecStartRequest)(nil),      // 17: pilot.v1.ExecStartRequest
	(*ExecStdin)(nil),             // 18: pilot.v1.ExecStdin
	(*ExecResize)(nil),            // 19: pilot.v1.ExecResize
	(*ExecCancelRequest)(nil),     // 20: pilot.v1.ExecCancelRequest
	(*ExecOutput)(nil),            // 21: pilot.v1.ExecOutput
	(*ExecEnd)(nil),               // 22: pilot.v1.ExecEnd
	(*HTTPHeader)(nil),            // 23: pilot.v1.HTTPHeader
	(*HTTPRequestStart)(nil),      // 24: pilot.v1.HTTPRequestStart
	(*HTTPResponseStart)(nil),     // 25: pilot.v1.HTTPResponseStart
	(*BodyChunk)(nil),             // 26: pilot.v1.BodyChunk
	(*BodyEnd)(nil),               // 27: pilot.v1.BodyEnd
	(*WSStartRequest)(nil),        // 28: pilot.v1.WSStartRequest
	(*WSFrame)(nil),               // 29: pilot.v1.WSFrame
	(*WSEnd)(nil),                 // 30: pilot.v1.WSEnd
}
var file_pilot_proto_depIdxs = []int32{
	1,  // 0: pilot.v1.WorkerMessage.register:type_name -> pilot.v1.RegisterRequest
	2,  // 1: pilot.v1.WorkerMessage.heartbeat:type_name -> pilot.v1.HeartbeatRequest
	3,  // 2: pilot.v1.WorkerMessage.resource_resp_start:type_name -> pilot.v1.ResourceResponseStart
	4,  // 3: pilot.v1.WorkerMessage.plugin_status:type_name -> pilot.v1.PluginStatusPush
	5,  // 4: pilot.v1.WorkerMessage.plugin_log:type_name -> pilot.v1.PluginLogChunk
	6,  // 5: pilot.v1.WorkerMessage.plugin_log_end:type_name -> pilot.v1.PluginLogEnd
	15, // 6: pilot.v1.WorkerMessage.logs_chunk:type_name -> pilot.v1.LogsChunk
	16, // 7: pilot.v1.WorkerMessage.logs_end:type_name -> pilot.v1.LogsEnd
	21, // 8: pilot.v1.WorkerMessage.exec_output:type_name -> pilot.v1.ExecOutput
	22, // 9: pilot.v1.WorkerMessage.exec_end:type_name -> pilot.v1.ExecEnd
	25, // 10: pilot.v1.WorkerMessage.http_resp_start:type_name -> pilot.v1.HTTPResponseStart
	29, // 11: pilot.v1.WorkerMessage.ws_frame_recv:type_name -> pilot.v1.WSFrame
	30, // 12: pilot.v1.WorkerMessage.ws_end_recv:type_name -> pilot.v1.WSEnd
	26, // 13: pilot.v1.WorkerMessage.body_chunk:type_name -> pilot.v1.BodyChunk
	27, // 14: pilot.v1.WorkerMessage.body_end:type_name -> pilot.v1.BodyEnd
	8,  // 15: pilot.v1.ServerMessage.register_ack:type_name -> pilot.v1.RegisterAck
	9,  // 16: pilot.v1.ServerMessage.resource_req_start:type_name -> pilot.v1.ResourceRequestStart
	10, // 17: pilot.v1.ServerMessage.plugin_cmd_start:type_name -> pilot.v1.PluginCommandStart
	13, // 18: pilot.v1.ServerMessage.logs_start:type_name -> pilot.v1.LogsStartRequest
	14, // 19: pilot.v1.ServerMessage.logs_cancel:type_name -> pilot.v1.LogsCancelRequest
	17, // 20: pilot.v1.ServerMessage.exec_start:type_name -> pilot.v1.ExecStartRequest
	18, // 21: pilot.v1.ServerMessage.exec_stdin:type_name -> pilot.v1.ExecStdin
	19, // 22: pilot.v1.ServerMessage.exec_resize:type_name -> pilot.v1.ExecResize
	20, // 23: pilot.v1.ServerMessage.exec_cancel:type_name -> pilot.v1.ExecCancelRequest
	24, // 24: pilot.v1.ServerMessage.http_req_start:type_name -> pilot.v1.HTTPRequestStart
	28, // 25: pilot.v1.ServerMessage.ws_start:type_name -> pilot.v1.WSStartRequest
	29, // 26: pilot.v1.ServerMessage.ws_frame_send:type_name -> pilot.v1.WSFrame
	30, // 27: pilot.v1.ServerMessage.ws_end_send:type_name -> pilot.v1.WSEnd
	26, // 28: pilot.v1.ServerMessage.body_chunk:type_name -> pilot.v1.BodyChunk
	27, // 29: pilot.v1.ServerMessage.body_end:type_name -> pilot.v1.BodyEnd
	11, // 30: pilot.v1.PluginCommandStart.spec:type_name -> pilot.v1.PluginSpec
	12, // 31: pilot.v1.PluginSpec.chart:type_name -> pilot.v1.ChartSource
	23, // 32: pilot.v1.HTTPRequestStart.headers:type_name -> pilot.v1.HTTPHeader
	23, // 33: pilot.v1.HTTPResponseStart.headers:type_name -> pilot.v1.HTTPHeader
	23, // 34: pilot.v1.WSStartRequest.headers:type_name -> pilot.v1.HTTPHeader
	0,  // 35: pilot.v1.PilotService.Connect:input_type -> pilot.v1.WorkerMessage
	7,  // 36: pilot.v1.PilotService.Connect:output_type -> pilot.v1.ServerMessage
	36, // [36:37] is the sub-list for method output_type
	35, // [35:36] is the sub-list for method input_type
	35, // [35:35] is the sub-list for extension type_name
	35, // [35:35] is the sub-list for extension extendee
	0,  // [0:35] is the sub-list for field type_name
}

func init() { file_pilot_proto_init() }
func file_pilot_proto_init() {
	if File_pilot_proto != nil {
		return
	}
	file_pilot_proto_msgTypes[0].OneofWrappers = []any{
		(*WorkerMessage_Register)(nil),
		(*WorkerMessage_Heartbeat)(nil),
		(*WorkerMessage_ResourceRespStart)(nil),
		(*WorkerMessage_PluginStatus)(nil),
		(*WorkerMessage_PluginLog)(nil),
		(*WorkerMessage_PluginLogEnd)(nil),
		(*WorkerMessage_LogsChunk)(nil),
		(*WorkerMessage_LogsEnd)(nil),
		(*WorkerMessage_ExecOutput)(nil),
		(*WorkerMessage_ExecEnd)(nil),
		(*WorkerMessage_HttpRespStart)(nil),
		(*WorkerMessage_WsFrameRecv)(nil),
		(*WorkerMessage_WsEndRecv)(nil),
		(*WorkerMessage_BodyChunk)(nil),
		(*WorkerMessage_BodyEnd)(nil),
	}
	file_pilot_proto_msgTypes[7].OneofWrappers = []any{
		(*ServerMessage_RegisterAck)(nil),
		(*ServerMessage_ResourceReqStart)(nil),
		(*ServerMessage_PluginCmdStart)(nil),
		(*ServerMessage_LogsStart)(nil),
		(*ServerMessage_LogsCancel)(nil),
		(*ServerMessage_ExecStart)(nil),
		(*ServerMessage_ExecStdin)(nil),
		(*ServerMessage_ExecResize)(nil),
		(*ServerMessage_ExecCancel)(nil),
		(*ServerMessage_HttpReqStart)(nil),
		(*ServerMessage_WsStart)(nil),
		(*ServerMessage_WsFrameSend)(nil),
		(*ServerMessage_WsEndSend)(nil),
		(*ServerMessage_BodyChunk)(nil),
		(*ServerMessage_BodyEnd)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pilot_proto_rawDesc), len(file_pilot_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   31,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pilot_proto_goTypes,
		DependencyIndexes: file_pilot_proto_depIdxs,
		MessageInfos:      file_pilot_proto_msgTypes,
	}.Build()
	File_pilot_proto = out.File
	file_pilot_proto_goTypes = nil
	file_pilot_proto_depIdxs = nil
}
