// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.11
// source: pilot.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// PilotServiceClient is the client API for PilotService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PilotServiceClient interface {
	// Worker 主动连接 Server，建立双向流
	Connect(ctx context.Context, opts ...grpc.CallOption) (PilotService_ConnectClient, error)
}

type pilotServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPilotServiceClient(cc grpc.ClientConnInterface) PilotServiceClient {
	return &pilotServiceClient{cc}
}

func (c *pilotServiceClient) Connect(ctx context.Context, opts ...grpc.CallOption) (PilotService_ConnectClient, error) {
	stream, err := c.cc.NewStream(ctx, &PilotService_ServiceDesc.Streams[0], "/pilot.v1.PilotService/Connect", opts...)
	if err != nil {
		return nil, err
	}
	x := &pilotServiceConnectClient{stream}
	return x, nil
}

type PilotService_ConnectClient interface {
	Send(*WorkerMessage) error
	Recv() (*ServerMessage, error)
	grpc.ClientStream
}

type pilotServiceConnectClient struct {
	grpc.ClientStream
}

func (x *pilotServiceConnectClient) Send(m *WorkerMessage) error {
	return x.ClientStream.SendMsg(m)
}

func (x *pilotServiceConnectClient) Recv() (*ServerMessage, error) {
	m := new(ServerMessage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// PilotServiceServer is the server API for PilotService service.
// All implementations must embed UnimplementedPilotServiceServer
// for forward compatibility
type PilotServiceServer interface {
	// Worker 主动连接 Server，建立双向流
	Connect(PilotService_ConnectServer) error
	mustEmbedUnimplementedPilotServiceServer()
}

// UnimplementedPilotServiceServer must be embedded to have forward compatible implementations.
type UnimplementedPilotServiceServer struct {
}

func (UnimplementedPilotServiceServer) Connect(PilotService_ConnectServer) error {
	return status.Errorf(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedPilotServiceServer) mustEmbedUnimplementedPilotServiceServer() {}

// UnsafePilotServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PilotServiceServer will
// result in compilation errors.
type UnsafePilotServiceServer interface {
	mustEmbedUnimplementedPilotServiceServer()
}

func RegisterPilotServiceServer(s grpc.ServiceRegistrar, srv PilotServiceServer) {
	s.RegisterService(&PilotService_ServiceDesc, srv)
}

func _PilotService_Connect_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PilotServiceServer).Connect(&pilotServiceConnectServer{stream})
}

type PilotService_ConnectServer interface {
	Send(*ServerMessage) error
	Recv() (*WorkerMessage, error)
	grpc.ServerStream
}

type pilotServiceConnectServer struct {
	grpc.ServerStream
}

func (x *pilotServiceConnectServer) Send(m *ServerMessage) error {
	return x.ServerStream.SendMsg(m)
}

func (x *pilotServiceConnectServer) Recv() (*WorkerMessage, error) {
	m := new(WorkerMessage)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// PilotService_ServiceDesc is the grpc.ServiceDesc for PilotService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PilotService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pilot.v1.PilotService",
	HandlerType: (*PilotServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Connect",
			Handler:       _PilotService_Connect_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "pilot.proto",
}
