// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: pilot.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WorkerMessage struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	RequestId string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"` // 空字符串表示 Push，非空表示 Response
	// Types that are valid to be assigned to Payload:
	//
	//	*WorkerMessage_Register
	//	*WorkerMessage_Heartbeat
	//	*WorkerMessage_NodeList
	//	*WorkerMessage_ResourceResp
	//	*WorkerMessage_PluginStatus
	Payload       isWorkerMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkerMessage) Reset() {
	*x = WorkerMessage{}
	mi := &file_pilot_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerMessage) ProtoMessage() {}

func (x *WorkerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pilot_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerMessage.ProtoReflect.Descriptor instead.
func (*WorkerMessage) Descriptor() ([]byte, []int) {
	return file_pilot_proto_rawDescGZIP(), []int{0}
}

func (x *WorkerMessage) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *WorkerMessage) GetPayload() isWorkerMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *WorkerMessage) GetRegister() *RegisterRequest {
	if x != nil {
		if x, ok := x.Payload.(*WorkerMessage_Register); ok {
			return x.Register
		}
	}
	return nil
}

func (x *WorkerMessage) GetHeartbeat() *HeartbeatRequest {
	if x != nil {
		if x, ok := x.Payload.(*WorkerMessage_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *WorkerMessage) GetNodeList() *NodeListPush {
	if x != nil {
		if x, ok := x.Payload.(*WorkerMessage_NodeList); ok {
			return x.NodeList
		}
	}
	return nil
}

func (x *WorkerMessage) GetResourceResp() *ResourceResponse {
	if x != nil {
		if x, ok := x.Payload.(*WorkerMessage_ResourceResp); ok {
			return x.ResourceResp
		}
	}
	return nil
}

func (x *WorkerMessage) GetPluginStatus() *PluginStatusPush {
	if x != nil {
		if x, ok := x.Payload.(*WorkerMessage_PluginStatus); ok {
			return x.PluginStatus
		}
	}
	return nil
}

type isWorkerMessage_Payload interface {
	isWorkerMessage_Payload()
}

type WorkerMessage_Register struct {
	Register *RegisterRequest `protobuf:"bytes,10,opt,name=register,proto3,oneof"`
}

type WorkerMessage_Heartbeat struct {
	Heartbeat *HeartbeatRequest `protobuf:"bytes,11,opt,name=heartbeat,proto3,oneof"`
}

type WorkerMessage_NodeList struct {
	NodeList *NodeListPush `protobuf:"bytes,20,opt,name=node_list,json=nodeList,proto3,oneof"`
}

type WorkerMessage_ResourceResp struct {
	ResourceResp *ResourceResponse `protobuf:"bytes,30,opt,name=resource_resp,json=resourceResp,proto3,oneof"`
}

type WorkerMessage_PluginStatus struct {
	PluginStatus *PluginStatusPush `protobuf:"bytes,40,opt,name=plugin_status,json=pluginStatus,proto3,oneof"`
}

func (*WorkerMessage_Register) isWorkerMessage_Payload() {}

func (*WorkerMessage_Heartbeat) isWorkerMessage_Payload() {}

func (*WorkerMessage_NodeList) isWorkerMessage_Payload() {}

func (*WorkerMessage_ResourceResp) isWorkerMessage_Payload() {}

func (*WorkerMessage_PluginStatus) isWorkerMessage_Payload() {}

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClusterToken  string                 `protobuf:"bytes,1,opt,name=cluster_token,json=clusterToken,proto3" json:"cluster_token,omitempty"`
	WorkerVersion string                 `protobuf:"bytes,2,opt,name=worker_version,json=workerVersion,proto3" json:"worker_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_pilot_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pilot_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_pilot_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterRequest) GetClusterToken() string {
	if x != nil {
		return x.ClusterToken
	}
	return ""
}

func (x *RegisterRequest) GetWorkerVersion() string {
	if x != nil {
		return x.WorkerVersion
	}
	return ""
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // unix seconds
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_pilot_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pilot_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_pilot_proto_rawDescGZIP(), []int{2}
}

func (x *HeartbeatRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type NodeListPush struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nodes         []*NodeInfo            `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeListPush) Reset() {
	*x = NodeListPush{}
	mi := &file_pilot_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeListPush) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeListPush) ProtoMessage() {}

func (x *NodeListPush) ProtoReflect() protoreflect.Message {
	mi := &file_pilot_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeListPush.ProtoReflect.Descriptor instead.
func (*NodeListPush) Descriptor() ([]byte, []int) {
	return file_pilot_proto_rawDescGZIP(), []int{3}
}

func (x *NodeListPush) GetNodes() []*NodeInfo {
	if x != nil {
		return x.Nodes
	}
	return nil
}

type NodeInfo struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Name   string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Status string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // Ready / NotReady / Unknown
	// 来自 node.Status.Capacity / Allocatable（millicores / bytes）
	CpuCapacity       int64             `protobuf:"varint,3,opt,name=cpu_capacity,json=cpuCapacity,proto3" json:"cpu_capacity,omitempty"`
	CpuAllocatable    int64             `protobuf:"varint,4,opt,name=cpu_allocatable,json=cpuAllocatable,proto3" json:"cpu_allocatable,omitempty"`
	MemoryCapacity    int64             `protobuf:"varint,5,opt,name=memory_capacity,json=memoryCapacity,proto3" json:"memory_capacity,omitempty"`
	MemoryAllocatable int64             `protobuf:"varint,6,opt,name=memory_allocatable,json=memoryAllocatable,proto3" json:"memory_allocatable,omitempty"`
	Labels            map[string]string `protobuf:"bytes,7,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Annotations       map[string]string `protobuf:"bytes,8,rep,name=annotations,proto3" json:"annotations,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// 来自 node.Status.NodeInfo
	OsImage          string `protobuf:"bytes,9,opt,name=os_image,json=osImage,proto3" json:"os_image,omitempty"` // e.g. "Ubuntu 24.04.4 LTS"
	KernelVersion    string `protobuf:"bytes,10,opt,name=kernel_version,json=kernelVersion,proto3" json:"kernel_version,omitempty"`
	ContainerRuntime string `protobuf:"bytes,11,opt,name=container_runtime,json=containerRuntime,proto3" json:"container_runtime,omitempty"` // e.g. "containerd://2.2.1"
	KubeletVersion   string `protobuf:"bytes,12,opt,name=kubelet_version,json=kubeletVersion,proto3" json:"kubelet_version,omitempty"`
	// 来自 node.Status.Addresses
	InternalIp string `protobuf:"bytes,13,opt,name=internal_ip,json=internalIp,proto3" json:"internal_ip,omitempty"`
	// 来自 node.Spec
	PodCidr       string `protobuf:"bytes,14,opt,name=pod_cidr,json=podCidr,proto3" json:"pod_cidr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeInfo) Reset() {
	*x = NodeInfo{}
	mi := &file_pilot_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeInfo) ProtoMessage() {}

func (x *NodeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pilot_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeInfo.ProtoReflect.Descriptor instead.
func (*NodeInfo) Descriptor() ([]byte, []int) {
	return file_pilot_proto_rawDescGZIP(), []int{4}
}

func (x *NodeInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NodeInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *NodeInfo) GetCpuCapacity() int64 {
	if x != nil {
		return x.CpuCapacity
	}
	return 0
}

func (x *NodeInfo) GetCpuAllocatable() int64 {
	if x != nil {
		return x.CpuAllocatable
	}
	return 0
}

func (x *NodeInfo) GetMemoryCapacity() int64 {
	if x != nil {
		return x.MemoryCapacity
	}
	return 0
}

func (x *NodeInfo) GetMemoryAllocatable() int64 {
	if x != nil {
		return x.MemoryAllocatable
	}
	return 0
}

func (x *NodeInfo) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *NodeInfo) GetAnnotations() map[string]string {
	if x != nil {
		return x.Annotations
	}
	return nil
}

func (x *NodeInfo) GetOsImage() string {
	if x != nil {
		return x.OsImage
	}
	return ""
}

func (x *NodeInfo) GetKernelVersion() string {
	if x != nil {
		return x.KernelVersion
	}
	return ""
}

func (x *NodeInfo) GetContainerRuntime() string {
	if x != nil {
		return x.ContainerRuntime
	}
	return ""
}

func (x *NodeInfo) GetKubeletVersion() string {
	if x != nil {
		return x.KubeletVersion
	}
	return ""
}

func (x *NodeInfo) GetInternalIp() string {
	if x != nil {
		return x.InternalIp
	}
	return ""
}

func (x *NodeInfo) GetPodCidr() string {
	if x != nil {
		return x.PodCidr
	}
	return ""
}

type ResourceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	Data          []byte                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"` // JSON 编码的 K8s 资源对象
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceResponse) Reset() {
	*x = ResourceResponse{}
	mi := &file_pilot_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceResponse) ProtoMessage() {}

func (x *ResourceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pilot_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceResponse.ProtoReflect.Descriptor instead.
func (*ResourceResponse) Descriptor() ([]byte, []int) {
	return file_pilot_proto_rawDescGZIP(), []int{5}
}

func (x *ResourceResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ResourceResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ResourceResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ResourceResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type PluginStatusPush struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PluginType    string                 `protobuf:"bytes,1,opt,name=plugin_type,json=pluginType,proto3" json:"plugin_type,omitempty"` // hami / victoria-metrics / victoria-logs / ...
	Phase         string                 `protobuf:"bytes,2,opt,name=phase,proto3" json:"phase,omitempty"`                             // Pending / Installing / Running / Failed
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginStatusPush) Reset() {
	*x = PluginStatusPush{}
	mi := &file_pilot_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginStatusPush) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginStatusPush) ProtoMessage() {}

func (x *PluginStatusPush) ProtoReflect() protoreflect.Message {
	mi := &file_pilot_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginStatusPush.ProtoReflect.Descriptor instead.
func (*PluginStatusPush) Descriptor() ([]byte, []int) {
	return file_pilot_proto_rawDescGZIP(), []int{6}
}

func (x *PluginStatusPush) GetPluginType() string {
	if x != nil {
		return x.PluginType
	}
	return ""
}

func (x *PluginStatusPush) GetPhase() string {
	if x != nil {
		return x.Phase
	}
	return ""
}

func (x *PluginStatusPush) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ServerMessage struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	RequestId string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ServerMessage_RegisterAck
	//	*ServerMessage_ResourceReq
	//	*ServerMessage_PluginCmd
	Payload       isServerMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerMessage) Reset() {
	*x = ServerMessage{}
	mi := &file_pilot_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMessage) ProtoMessage() {}

func (x *ServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pilot_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMessage.ProtoReflect.Descriptor instead.
func (*ServerMessage) Descriptor() ([]byte, []int) {
	return file_pilot_proto_rawDescGZIP(), []int{7}
}

func (x *ServerMessage) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ServerMessage) GetPayload() isServerMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ServerMessage) GetRegisterAck() *RegisterAck {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_RegisterAck); ok {
			return x.RegisterAck
		}
	}
	return nil
}

func (x *ServerMessage) GetResourceReq() *ResourceRequest {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_ResourceReq); ok {
			return x.ResourceReq
		}
	}
	return nil
}

func (x *ServerMessage) GetPluginCmd() *PluginCommand {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_PluginCmd); ok {
			return x.PluginCmd
		}
	}
	return nil
}

type isServerMessage_Payload interface {
	isServerMessage_Payload()
}

type ServerMessage_RegisterAck struct {
	RegisterAck *RegisterAck `protobuf:"bytes,10,opt,name=register_ack,json=registerAck,proto3,oneof"`
}

type ServerMessage_ResourceReq struct {
	ResourceReq *ResourceRequest `protobuf:"bytes,20,opt,name=resource_req,json=resourceReq,proto3,oneof"`
}

type ServerMessage_PluginCmd struct {
	PluginCmd *PluginCommand `protobuf:"bytes,30,opt,name=plugin_cmd,json=pluginCmd,proto3,oneof"`
}

func (*ServerMessage_RegisterAck) isServerMessage_Payload() {}

func (*ServerMessage_ResourceReq) isServerMessage_Payload() {}

func (*ServerMessage_PluginCmd) isServerMessage_Payload() {}

type RegisterAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ClusterId     string                 `protobuf:"bytes,2,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterAck) Reset() {
	*x = RegisterAck{}
	mi := &file_pilot_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterAck) ProtoMessage() {}

func (x *RegisterAck) ProtoReflect() protoreflect.Message {
	mi := &file_pilot_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterAck.ProtoReflect.Descriptor instead.
func (*RegisterAck) Descriptor() ([]byte, []int) {
	return file_pilot_proto_rawDescGZIP(), []int{8}
}

func (x *RegisterAck) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterAck) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *RegisterAck) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ResourceRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Action    string                 `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"`       // list / get / apply / delete
	Group     string                 `protobuf:"bytes,2,opt,name=group,proto3" json:"group,omitempty"`         // apps / "" / ...
	Version   string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`     // v1 / v1beta1 / ...
	Kind      string                 `protobuf:"bytes,4,opt,name=kind,proto3" json:"kind,omitempty"`           // Deployment / Pod / Service / ...
	Namespace string                 `protobuf:"bytes,5,opt,name=namespace,proto3" json:"namespace,omitempty"` // 空表示 cluster-scoped
	Name      string                 `protobuf:"bytes,6,opt,name=name,proto3" json:"name,omitempty"`           // list 时为空
	Body      []byte                 `protobuf:"bytes,7,opt,name=body,proto3" json:"body,omitempty"`           // apply 时为 JSON manifest
	// list 分页：0 表示不限制，非空 continue_token 表示取下一页
	Limit         int64  `protobuf:"varint,8,opt,name=limit,proto3" json:"limit,omitempty"`
	ContinueToken string `protobuf:"bytes,9,opt,name=continue_token,json=continueToken,proto3" json:"continue_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceRequest) Reset() {
	*x = ResourceRequest{}
	mi := &file_pilot_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceRequest) ProtoMessage() {}

func (x *ResourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pilot_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceRequest.ProtoReflect.Descriptor instead.
func (*ResourceRequest) Descriptor() ([]byte, []int) {
	return file_pilot_proto_rawDescGZIP(), []int{9}
}

func (x *ResourceRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *ResourceRequest) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *ResourceRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ResourceRequest) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *ResourceRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *ResourceRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ResourceRequest) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *ResourceRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ResourceRequest) GetContinueToken() string {
	if x != nil {
		return x.ContinueToken
	}
	return ""
}

type PluginCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Action        string                 `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"`                           // enable / disable
	PluginType    string                 `protobuf:"bytes,2,opt,name=plugin_type,json=pluginType,proto3" json:"plugin_type,omitempty"` // hami / victoria-metrics / victoria-logs / ...
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Values        []byte                 `protobuf:"bytes,4,opt,name=values,proto3" json:"values,omitempty"` // JSON 编码的 Helm values
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginCommand) Reset() {
	*x = PluginCommand{}
	mi := &file_pilot_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginCommand) ProtoMessage() {}

func (x *PluginCommand) ProtoReflect() protoreflect.Message {
	mi := &file_pilot_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginCommand.ProtoReflect.Descriptor instead.
func (*PluginCommand) Descriptor() ([]byte, []int) {
	return file_pilot_proto_rawDescGZIP(), []int{10}
}

func (x *PluginCommand) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *PluginCommand) GetPluginType() string {
	if x != nil {
		return x.PluginType
	}
	return ""
}

func (x *PluginCommand) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *PluginCommand) GetValues() []byte {
	if x != nil {
		return x.Values
	}
	return nil
}

var File_pilot_proto protoreflect.FileDescriptor

const file_pilot_proto_rawDesc = "" +
	"\n" +
	"\vpilot.proto\x12\bpilot.v1\"\xeb\x02\n" +
	"\rWorkerMessage\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x127\n" +
	"\bregister\x18\n" +
	" \x01(\v2\x19.pilot.v1.RegisterRequestH\x00R\bregister\x12:\n" +
	"\theartbeat\x18\v \x01(\v2\x1a.pilot.v1.HeartbeatRequestH\x00R\theartbeat\x125\n" +
	"\tnode_list\x18\x14 \x01(\v2\x16.pilot.v1.NodeListPushH\x00R\bnodeList\x12A\n" +
	"\rresource_resp\x18\x1e \x01(\v2\x1a.pilot.v1.ResourceResponseH\x00R\fresourceResp\x12A\n" +
	"\rplugin_status\x18( \x01(\v2\x1a.pilot.v1.PluginStatusPushH\x00R\fpluginStatusB\t\n" +
	"\apayload\"]\n" +
	"\x0fRegisterRequest\x12#\n" +
	"\rcluster_token\x18\x01 \x01(\tR\fclusterToken\x12%\n" +
	"\x0eworker_version\x18\x02 \x01(\tR\rworkerVersion\"0\n" +
	"\x10HeartbeatRequest\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\"8\n" +
	"\fNodeListPush\x12(\n" +
	"\x05nodes\x18\x01 \x03(\v2\x12.pilot.v1.NodeInfoR\x05nodes\"\xa8\x05\n" +
	"\bNodeInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12!\n" +
	"\fcpu_capacity\x18\x03 \x01(\x03R\vcpuCapacity\x12'\n" +
	"\x0fcpu_allocatable\x18\x04 \x01(\x03R\x0ecpuAllocatable\x12'\n" +
	"\x0fmemory_capacity\x18\x05 \x01(\x03R\x0ememoryCapacity\x12-\n" +
	"\x12memory_allocatable\x18\x06 \x01(\x03R\x11memoryAllocatable\x126\n" +
	"\x06labels\x18\a \x03(\v2\x1e.pilot.v1.NodeInfo.LabelsEntryR\x06labels\x12E\n" +
	"\vannotations\x18\b \x03(\v2#.pilot.v1.NodeInfo.AnnotationsEntryR\vannotations\x12\x19\n" +
	"\bos_image\x18\t \x01(\tR\aosImage\x12%\n" +
	"\x0ekernel_version\x18\n" +
	" \x01(\tR\rkernelVersion\x12+\n" +
	"\x11container_runtime\x18\v \x01(\tR\x10containerRuntime\x12'\n" +
	"\x0fkubelet_version\x18\f \x01(\tR\x0ekubeletVersion\x12\x1f\n" +
	"\vinternal_ip\x18\r \x01(\tR\n" +
	"internalIp\x12\x19\n" +
	"\bpod_cidr\x18\x0e \x01(\tR\apodCidr\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a>\n" +
	"\x10AnnotationsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"u\n" +
	"\x10ResourceResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\x12\x12\n" +
	"\x04data\x18\x04 \x01(\fR\x04data\"c\n" +
	"\x10PluginStatusPush\x12\x1f\n" +
	"\vplugin_type\x18\x01 \x01(\tR\n" +
	"pluginType\x12\x14\n" +
	"\x05phase\x18\x02 \x01(\tR\x05phase\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\xef\x01\n" +
	"\rServerMessage\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12:\n" +
	"\fregister_ack\x18\n" +
	" \x01(\v2\x15.pilot.v1.RegisterAckH\x00R\vregisterAck\x12>\n" +
	"\fresource_req\x18\x14 \x01(\v2\x19.pilot.v1.ResourceRequestH\x00R\vresourceReq\x128\n" +
	"\n" +
	"plugin_cmd\x18\x1e \x01(\v2\x17.pilot.v1.PluginCommandH\x00R\tpluginCmdB\t\n" +
	"\apayload\"`\n" +
	"\vRegisterAck\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x02 \x01(\tR\tclusterId\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\xf0\x01\n" +
	"\x0fResourceRequest\x12\x16\n" +
	"\x06action\x18\x01 \x01(\tR\x06action\x12\x14\n" +
	"\x05group\x18\x02 \x01(\tR\x05group\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12\x12\n" +
	"\x04kind\x18\x04 \x01(\tR\x04kind\x12\x1c\n" +
	"\tnamespace\x18\x05 \x01(\tR\tnamespace\x12\x12\n" +
	"\x04name\x18\x06 \x01(\tR\x04name\x12\x12\n" +
	"\x04body\x18\a \x01(\fR\x04body\x12\x14\n" +
	"\x05limit\x18\b \x01(\x03R\x05limit\x12%\n" +
	"\x0econtinue_token\x18\t \x01(\tR\rcontinueToken\"z\n" +
	"\rPluginCommand\x12\x16\n" +
	"\x06action\x18\x01 \x01(\tR\x06action\x12\x1f\n" +
	"\vplugin_type\x18\x02 \x01(\tR\n" +
	"pluginType\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12\x16\n" +
	"\x06values\x18\x04 \x01(\fR\x06values2O\n" +
	"\fPilotService\x12?\n" +
	"\aConnect\x12\x17.pilot.v1.WorkerMessage\x1a\x17.pilot.v1.ServerMessage(\x010\x01B5Z3github.com/togettoyou/kpilot/pkg/common/proto;protob\x06proto3"

var (
	file_pilot_proto_rawDescOnce sync.Once
	file_pilot_proto_rawDescData []byte
)

func file_pilot_proto_rawDescGZIP() []byte {
	file_pilot_proto_rawDescOnce.Do(func() {
		file_pilot_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pilot_proto_rawDesc), len(file_pilot_proto_rawDesc)))
	})
	return file_pilot_proto_rawDescData
}

var file_pilot_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_pilot_proto_goTypes = []any{
	(*WorkerMessage)(nil),    // 0: pilot.v1.WorkerMessage
	(*RegisterRequest)(nil),  // 1: pilot.v1.RegisterRequest
	(*HeartbeatRequest)(nil), // 2: pilot.v1.HeartbeatRequest
	(*NodeListPush)(nil),     // 3: pilot.v1.NodeListPush
	(*NodeInfo)(nil),         // 4: pilot.v1.NodeInfo
	(*ResourceResponse)(nil), // 5: pilot.v1.ResourceResponse
	(*PluginStatusPush)(nil), // 6: pilot.v1.PluginStatusPush
	(*ServerMessage)(nil),    // 7: pilot.v1.ServerMessage
	(*RegisterAck)(nil),      // 8: pilot.v1.RegisterAck
	(*ResourceRequest)(nil),  // 9: pilot.v1.ResourceRequest
	(*PluginCommand)(nil),    // 10: pilot.v1.PluginCommand
	nil,                      // 11: pilot.v1.NodeInfo.LabelsEntry
	nil,                      // 12: pilot.v1.NodeInfo.AnnotationsEntry
}
var file_pilot_proto_depIdxs = []int32{
	1,  // 0: pilot.v1.WorkerMessage.register:type_name -> pilot.v1.RegisterRequest
	2,  // 1: pilot.v1.WorkerMessage.heartbeat:type_name -> pilot.v1.HeartbeatRequest
	3,  // 2: pilot.v1.WorkerMessage.node_list:type_name -> pilot.v1.NodeListPush
	5,  // 3: pilot.v1.WorkerMessage.resource_resp:type_name -> pilot.v1.ResourceResponse
	6,  // 4: pilot.v1.WorkerMessage.plugin_status:type_name -> pilot.v1.PluginStatusPush
	4,  // 5: pilot.v1.NodeListPush.nodes:type_name -> pilot.v1.NodeInfo
	11, // 6: pilot.v1.NodeInfo.labels:type_name -> pilot.v1.NodeInfo.LabelsEntry
	12, // 7: pilot.v1.NodeInfo.annotations:type_name -> pilot.v1.NodeInfo.AnnotationsEntry
	8,  // 8: pilot.v1.ServerMessage.register_ack:type_name -> pilot.v1.RegisterAck
	9,  // 9: pilot.v1.ServerMessage.resource_req:type_name -> pilot.v1.ResourceRequest
	10, // 10: pilot.v1.ServerMessage.plugin_cmd:type_name -> pilot.v1.PluginCommand
	0,  // 11: pilot.v1.PilotService.Connect:input_type -> pilot.v1.WorkerMessage
	7,  // 12: pilot.v1.PilotService.Connect:output_type -> pilot.v1.ServerMessage
	12, // [12:13] is the sub-list for method output_type
	11, // [11:12] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_pilot_proto_init() }
func file_pilot_proto_init() {
	if File_pilot_proto != nil {
		return
	}
	file_pilot_proto_msgTypes[0].OneofWrappers = []any{
		(*WorkerMessage_Register)(nil),
		(*WorkerMessage_Heartbeat)(nil),
		(*WorkerMessage_NodeList)(nil),
		(*WorkerMessage_ResourceResp)(nil),
		(*WorkerMessage_PluginStatus)(nil),
	}
	file_pilot_proto_msgTypes[7].OneofWrappers = []any{
		(*ServerMessage_RegisterAck)(nil),
		(*ServerMessage_ResourceReq)(nil),
		(*ServerMessage_PluginCmd)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pilot_proto_rawDesc), len(file_pilot_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pilot_proto_goTypes,
		DependencyIndexes: file_pilot_proto_depIdxs,
		MessageInfos:      file_pilot_proto_msgTypes,
	}.Build()
	File_pilot_proto = out.File
	file_pilot_proto_goTypes = nil
	file_pilot_proto_depIdxs = nil
}
