// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import ClusterOutlined from '/Users/guoqi/GolandProjects/kpilot/web/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/ClusterOutlined';
import ThunderboltOutlined from '/Users/guoqi/GolandProjects/kpilot/web/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/ThunderboltOutlined';
import BulbOutlined from '/Users/guoqi/GolandProjects/kpilot/web/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/BulbOutlined';
import AppstoreOutlined from '/Users/guoqi/GolandProjects/kpilot/web/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/AppstoreOutlined';
export default { ClusterOutlined, ThunderboltOutlined, BulbOutlined, AppstoreOutlined };
