// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
// defineApp
export { defineApp } from './core/defineApp'
export type { RuntimeConfig } from './core/defineApp'
// plugins
export { Access, useAccess, useAccessMarkedRoutes } from '/Users/guoqi/GolandProjects/kpilot/web/src/.umi-undefined/plugin-access';
export { useAntdConfig, useAntdConfigSetter } from '/Users/guoqi/GolandProjects/kpilot/web/src/.umi-undefined/plugin-antd';
export { addLocale, setLocale, getLocale, getIntl, useIntl, injectIntl, formatMessage, FormattedMessage, getAllLocales, FormattedDate, FormattedDateParts, FormattedDisplayName, FormattedHTMLMessage, FormattedList, FormattedNumber, FormattedNumberParts, FormattedPlural, FormattedRelativeTime, FormattedTime, FormattedTimeParts, IntlProvider, RawIntlProvider, SelectLang } from '/Users/guoqi/GolandProjects/kpilot/web/src/.umi-undefined/plugin-locale';
export { Provider, useModel } from '/Users/guoqi/GolandProjects/kpilot/web/src/.umi-undefined/plugin-model';
export { useRequest, UseRequestProvider, request, getRequestInstance } from '/Users/guoqi/GolandProjects/kpilot/web/src/.umi-undefined/plugin-request';
// plugins types.d.ts
export * from '/Users/guoqi/GolandProjects/kpilot/web/src/.umi-undefined/plugin-access/types.d';
export * from '/Users/guoqi/GolandProjects/kpilot/web/src/.umi-undefined/plugin-antd/types.d';
export * from '/Users/guoqi/GolandProjects/kpilot/web/src/.umi-undefined/plugin-layout/types.d';
export * from '/Users/guoqi/GolandProjects/kpilot/web/src/.umi-undefined/plugin-request/types.d';
// @umijs/renderer-*
export { createBrowserHistory, createHashHistory, createMemoryHistory, Helmet, HelmetProvider, createSearchParams, generatePath, matchPath, matchRoutes, Navigate, NavLink, Outlet, resolvePath, useLocation, useMatch, useNavigate, useOutlet, useOutletContext, useParams, useResolvedPath, useRoutes, useSearchParams, useAppData, useClientLoaderData, useLoaderData, useRouteProps, useSelectedRoutes, useServerLoaderData, renderClient, __getRoot, Link, useRouteData, __useFetcher, withRouter } from '/Users/guoqi/GolandProjects/kpilot/web/node_modules/@umijs/renderer-react';
export type { History, ClientLoader } from '/Users/guoqi/GolandProjects/kpilot/web/node_modules/@umijs/renderer-react'
// umi/client/client/plugin
export { ApplyPluginsType, PluginManager } from '/Users/guoqi/GolandProjects/kpilot/web/node_modules/umi/client/client/plugin.js';
export { history, createHistory } from './core/history';
export { terminal } from './core/terminal';
// react ssr
export const useServerInsertedHTML: Function = () => {};
