{
 "title": "VictoriaLogs - Explorer K8S (pods)",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "ds",
    "label": "DS",
    "query": "victoriametrics-logs-datasource"
   },
   { "name": "namespace", "label": "NS", "query": { "query": "{}" } },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "{kubernetes.pod_namespace in($namespace)}"
    }
   },
   {
    "name": "container",
    "label": "Container",
    "query": {
     "query": "{kubernetes.pod_namespace in($namespace), kubernetes.pod_name=~\"$pod.*\"}"
    }
   },
   {
    "name": "level",
    "label": "Level",
    "query": {
     "query": "{kubernetes.pod_namespace in($namespace), kubernetes.container_name in($container)} | format if (log.level:\"\") \"unknown\" as log.level "
    }
   },
   { "name": "limit", "label": "Limit", "query": "500,1000,2500,5000" },
   { "name": "filter", "label": "Filter" }
  ]
 },
 "panels": [
  {
   "title": "Info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 1 },
     "options": {
      "content": "- The dashboard filters data by `container name`. The data may not be displayed correctly if several containers have the same name"
     }
    }
   ]
  },
  { "title": "Logs by Namespace ($namespace)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Namespace",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{kubernetes.pod_namespace in($namespace)}\r\n| stats by (kubernetes.pod_namespace) count()\r\n| count()"
    }
   ]
  },
  {
   "title": "Container",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{kubernetes.pod_namespace in($namespace)}\r\n| stats by (kubernetes.container_name) count()\r\n| count()"
    }
   ]
  },
  {
   "title": "Logs by level",
   "type": "stat",
   "gridPos": { "h": 3, "w": 18, "x": 6, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{kubernetes.pod_namespace in($namespace)}\r\n| format if (log.level:\"\") \"unknown\" as log.level\r\n| log.level:in($level)\r\n| stats by (log.level) count()",
     "legendFormat": "{{ log.level }}"
    }
   ]
  },
  {
   "title": "Top 5 logs by namespace",
   "type": "table",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "{kubernetes.pod_namespace in($namespace)}\r\n| stats by (kubernetes.pod_namespace) count() hits\r\n| sort by (hits) desc\r\n| limit 5"
    }
   ]
  },
  {
   "title": "Logs total by namespace/container",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 18, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "{kubernetes.pod_namespace in($namespace), kubernetes.pod_name=~\"$pod.*\"}\r\n| format if (log.level:\"\") \"unknown\" as log.level\r\n| log.level:in($level)\r\n| stats by (kubernetes.pod_namespace,kubernetes.pod_name,kubernetes.container_name) count() logs_total",
     "legendFormat": "{{kubernetes.pod_namespace}}/{{kubernetes.pod_name}}/{{kubernetes.container_name}}"
    }
   ]
  },
  {
   "title": "Top 5 logs by containers",
   "type": "table",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "{kubernetes.pod_namespace in($namespace), kubernetes.pod_name=~\"$pod.*\"}\r\n| stats by (kubernetes.container_name) count() hits\r\n| sort by (hits) desc\r\n| limit 5"
    }
   ]
  },
  {
   "title": "Logs rate by namespace/container",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 18, "x": 6, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "{kubernetes.pod_namespace in($namespace), kubernetes.pod_name=~\"$pod.*\"}\r\n| format if (log.level:\"\") \"unknown\" as log.level\r\n| log.level:in($level)\r\n| stats by (kubernetes.pod_namespace,kubernetes.pod_name,kubernetes.container_name) rate() logs_rate\r\n| filter logs_rate: > 0",
     "legendFormat": "{{kubernetes.pod_namespace}}/{{kubernetes.pod_name}}/{{kubernetes.container_name}}"
    }
   ]
  },
  { "title": "Logs by Container ($container)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Logs by container",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "{kubernetes.pod_namespace in($namespace), kubernetes.container_name in($container), kubernetes.pod_name=~\"$pod.*\"}\r\n| format if (log.level:\"\") \"unknown\" as log.level\r\n| log.level:in($level)\r\n| stats by (kubernetes.container_name) count() hits\r\n| sort by (hits) desc"
    }
   ]
  },
  {
   "title": "Logs volume",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 18, "x": 6, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "{kubernetes.pod_namespace in($namespace), kubernetes.container_name in($container), kubernetes.pod_name=~\"$pod.*\"}\r\n| format if (log.level:\"\") \"unknown\" as log.level\r\n| log.level:in($level)\r\n| stats by (log.level) count()",
     "legendFormat": "{{ log.level }}"
    }
   ]
  },
  {
   "title": "Logs raw",
   "type": "logs",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 31 },
   "targets": [
    {
     "direction": "desc",
     "expr": "{kubernetes.pod_namespace in($namespace), kubernetes.container_name in($container), kubernetes.pod_name=~\"$pod.*\"}\r\n| format if (log.level:\"\") \"unknown\" as log.level\r\n| log.level:in($level)\r\n| sort by (_time) desc\r\n| limit $limit",
     "maxLines": 5000
    }
   ]
  }
 ]
}